### ISSUE TITLE
New Clojure files sometime have an extra space

### ISSUE THREAD

**Issue by danielcompton** [cursive-ide/cursive#1082]
I don't remember what I did to get this to happen, but sometimes when I create a new file using Cursive, the ns declaration has an extra space in front. So instead of

``` clj
(ns myns.example)
```

it would be:

``` clj
 (ns myns.example)
```

I'll add reproduction steps the next time I notice it happening.

**Comment by danielcompton** [comment]
I've figured out how to reproduce it:

1. In the IntelliJ sidebar, create a new file in a folder that is not a Clojure source root
2. Type in a namespace

Observe that the newly created file has a space in front of the `ns` declaration.

**Comment by cursive-ide** [comment]
This issue is fixed, sort of. The problem with the space was an issue with the template, which is fixed. However, a larger issue is that namespace creation under non-source roots is pretty fundamentally broken anyway, to the point where I'm happy to say it's not supported. This is due to the way that the IntelliJ file creation from templates works - IntelliJ automatically creates the intermediate directories required from the file name (i.e. the packages, in the case of Clojure), and then uses the final ns segment as the file name. It then passes the package name and the file name to the file template, as the `$PACKAGE_NAME` and `$NAME` variables. However it calculates the package name from the directories between the new file and its nearest source root, not from the name entered in the new file dialog. This makes sense, since it's possible to create a file inside a `foo.bar` directory, enter the ns name as `baz` and get the file in the correct location with the ns declaration `(ns foo.bar.baz)`. However this is obviously broken if IntelliJ can't find a source root for the file. 

What all this means is that if you create a new namespace inside a non-source-root dir and enter `foo.bar.baz` as the namespace name, IntelliJ will create the `foo` and `bar` directories and create `baz.clj` in that directory, but it cannot pass the package name to the file template, and the file will be created with `(ns baz)`, which is incorrect. I can't see a good workaround for this, unfortunately.
