### ISSUE TITLE
Meta key is bound to several commands in the Cursive binding set under Windows

### ISSUE THREAD

**Issue by imrekoszo** [cursive-ide/cursive#1139]
Using a fresh install of:
- Windows 7 SP1 x64
- IntelliJ IDEA 15.0
- Build #IC-143.381, built on October 30, 2015
- JRE: 1.8.0_51-b16 x86
- JVM: Java HotSpot(TM) Server VM by Oracle Corporation
- Cursive 0.1.68
1. open settings in idea
2. under Keymap/Clojure keybindings select Cursive from the dropdown
   - several bindings have the Meta key in them, one even has Meta+Alt, see attached screenshot
     ![2015-11-04 11_34_48-settings](https://cloud.githubusercontent.com/assets/1116295/10965537/94df12e6-83a5-11e5-9115-025ff26f9283.png)

(emacs bindings don't appear to be affected)

**Comment by pupeno** [comment]
I just suffered from this same issue. I though meta was all until I found meta+alt+k.

**Comment by hujianxin** [comment]
Anyone can help?

**Comment by shmup** [comment]
So you cannot change the bindings under **Keymap > Clojure Keybindings** but you can find and update them under the general Keymap pane. In the screenshot you can see I updated **Barf Backwards** and **Slurp Backwards** to use <kbd>Alt</kbd> instead of <kbd>Meta</kbd>.

There were some conflicts with another setting using those bindings, but they weren't important to me and I overwrote them. You could assign something else to them, of course.

![image](https://user-images.githubusercontent.com/118710/30068256-2d44f006-922b-11e7-9a02-c8cf71624292.png)

**Comment by cursive-ide** [comment]
This has been fixed in #1863.
