### ISSUE TITLE
Integrate parinfer functionality

### ISSUE THREAD

**Issue by extesy** [cursive-ide/cursive#1155]
Take a look at examples on https://shaunlebron.github.io/parinfer/index.html - this is pure magic. I really would like cursive to be able to do that.

**Comment by aadrian** [comment]
+1 
even the docs are great :).

IMHO this should be the default edit mode for Cursive, since it's much more efficient for new users.

**Comment by cursiveclojure** [comment]
Yes, this looks very nice indeed.

**Comment by wilkerlucio** [comment]
Interesting, I would like to see that landing on Cursive at some point.

**Comment by jhalterman** [comment]
:+1:  :+1:  :+1:  :+1:  :+1: 

That indent mode stuff is just great. I agree with @extesy - that kind of magic would be great.

**Comment by mking** [comment]
:+1: This would be great to have as an option. One of the things I like about Cursive is that the learning curve isn't too steep (unlike, say, Emacs), and I think this would be an improvement in that direction.

**Comment by yusefnapora** [comment]
:+1: 

I'd love to have parinfer available in Cursive.  Using it in Atom actually makes me feel like I'm better at writing clojure, since the bit of "syntactic friction" is removed & I'm not dragged out of my mental model of the code by formatting concerns.  It's not enough to make me pick Atom over Cursive, but it's the one thing I miss.

 Just wanted to point out that the "official" [parinfer](https://github.com/shaunlebron/parinfer) implementation was just split out into a standalone library, with the codemirror stuff in a separate namespace.  So that should make it simpler to integrate if you're planning to use the reference implementation.  I'm not sure how nicely that would play with the existing structural editing in Cursive, but if you want to treat them as separate mutually exclusive modes, you could probably use the reference implementation and just let it operate on the raw text of the document.

**Comment by simax** [comment]
I too would really love to see parinfer in Cursive.  :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by pbaille** [comment]
:+1:

**Comment by alphaone** [comment]
:+1:

**Comment by squest** [comment]
:+1:

**Comment by d-r** [comment]
:+1:

**Comment by vincent-dm** [comment]
+1

**Comment by qwtel** [comment]
Hard to switch back after getting used to it in atom.

**Comment by NeCkEr** [comment]
+1

**Comment by CmdrDats** [comment]
:+1: definitely would love to see this integrated!

**Comment by erichmond** [comment]
:+1: Would be great

**Comment by SerCeMan** [comment]
:+1:

**Comment by damassi** [comment]
@shaunlebron and @oakmac - I'm sure you're both already aware of this issue but wanted to ping you just in case. What an awesome combo this would be.

**Comment by shaunlebron** [comment]
I want to mention a few recent developments that may make integration easier:

- parinfer is now a single, imperative JS file (see [parinfer.js]), which should be much simpler to port to Java for use in Cursive
- [test code] is very short since the test cases are represented in json, so it should be easy to test/verify a Java port
- [benchmarks] show that our new imperative implementation can parse about ~50 lines/ms on Node, so performance may be similar on the JVM.

[parinfer.js]:https://github.com/shaunlebron/parinfer/blob/master/lib/parinfer.js
[test code]:https://github.com/shaunlebron/parinfer/blob/master/lib/test/test.js
[benchmarks]:https://gist.github.com/shaunlebron/d19f3b0d54c1ad794235

**Comment by cursive-ide** [comment]
Thanks @shaunlebron, that's very helpful. I'll take a look at the JS implementation - I'll probably have to modify it a bit to work in Cursive since Cursive already has its own lexer but it'll be a good base to start from.

**Comment by avocade** [comment]
+1

**Comment by dhruvbhatia** [comment]
:+1:

**Comment by j-pb** [comment]
Want :D :+1:

**Comment by joshhill** [comment]
+1

**Comment by colinyip** [comment]
+1

**Comment by akovantsev** [comment]
:+1:

**Comment by dl1ely** [comment]
The only thing that keeps me on Atom. Please make it happen in Cursive!

**Comment by yeonsh** [comment]
:+1:

**Comment by oakmac** [comment]
Hi folks!

I just wrote a [JVM port of Parinfer]. Should help make this task much easier.

[JVM port of Parinfer]:https://github.com/oakmac/parinfer-jvm

**Comment by tuhlmann** [comment]
:+1:

**Comment by damassi** [comment]
@cursive-ide - do you have any plans on integrating this in? Or is it still in the "nice-to-have" category? I know there are a lot of +1's here, but Parinfer is really a delight to work with and I feel will help advance the adoption of Clojure quite significantly if fully appreciated.

**Comment by cursive-ide** [comment]
@damassi Yes, I'm actually working on this now but it's a little tricky to integrate into IntelliJ. It should be in the next release.

**Comment by damassi** [comment]
Incredible. Thanks so much @cursive-ide, @oakmac and @shaunlebron!

**Comment by lucian303** [comment]
:+1:

**Comment by vincentjames501** [comment]
+1

**Comment by neverfox** [comment]
Oh wow, this is the best news.

**Comment by vincent-dm** [comment]
@cursive-ide any idea when the next release will be?

**Comment by cursive-ide** [comment]
@vincent-dm Hopefully within a week or so, it's been trickier than I expected.

**Comment by extesy** [comment]
@cursive-ide Parinfer integration looks great, thanks for adding it! I see that you have not included paren mode, but I found it useful for preserving identation like in the 5-th example on https://shaunlebron.github.io/parinfer/ page. Could you please add an exception for at least that one case?

**Comment by cursive-ide** [comment]
@extesy Yes, I'm going to try to make an indentation preserving mode which will work in both paredit mode and with structural editing totally off.

**Comment by johanhaleby** [comment]
Do you have to enable parinfer in Cursive in any other way than just switching it on here:

![image](https://cloud.githubusercontent.com/assets/187029/13912919/205bd81a-ef42-11e5-890f-5e2aba6ef938.png)

I don't notice any difference to "off"? How can I check if it's working? I've seen the animations on parinfer's website but Cursive doesn't behave like that? For example the "Preserve indentation" example doesn't work for me.

**Comment by cursive-ide** [comment]
No, that should be it, although a few people have reported having to toggle it twice for some reason.

Note that Cursive only implements indent mode, not paren mode (which maintains indentation). So as you indent and dedent code, you should see the parentheses being moved around. See the first example here: http://shaunlebron.github.io/parinfer/

**Comment by j-pb** [comment]
Doesn't work for me as well.
It does the initial indentation, but then behaves just like no structural editing.

Indentation doesn't cause parenthesis to move,
and deletion takes the content after the caret to the line above once one deletes past the recommended indentation point.

**Comment by pbaille** [comment]
:+1:

**Comment by cursive-ide** [comment]
@johanhaleby @j-pb I've just found a bug where parinfer doesn't work correctly in the REPL editor. Were you trying to use it in the REPL editor when it didn't work?

**Comment by cursive-ide** [comment]
Actually, I have found at least one case where parinfer broke existing code (shaunlebron/parinfer#106). In this case, parinfer appeared to do nothing because Cursive is not correctly reporting the parinfer error cases. I'll fix that so at least it's obvious why things aren't working.

**Comment by johanhaleby** [comment]
I think my REPL was open when I switched to parinfer but I haven't tried using it in the REPL.

**Comment by pbaille** [comment]
@cursive-ide just to know, have you planed to implement paren mode in the future?

**Comment by j-pb** [comment]
No. Just the plain editor.

cheers Jan

**Comment by cursive-ide** [comment]
@pbaille I hadn't, since I believed that indent mode is the only useful mode for actually editing - paren mode is still used internally. However there's some doubt about this now, and in fact there's some doubt about it in general (see [here](https://github.com/noctuid/parinfer-notes) for an example). 

For non-indent mode editing modes (paredit, and no structural editing at all), I'm planning to implement a paren-mode lite which will maintain indentation as well as it can. I believe this is the main benefit of paren mode.

**Comment by neverfox** [comment]
Yes, paren is an essentialy part of parinfer usability from what I can tell. With just indent mode you end up in trouble in fairly common cases:

Indent mode
```
|(d/q '[:find ?e
        :where [?e ?a ?v]]
      db)
```
Now start trying to wrap in a `(take n coll)`:
```
(take 5 (d/q '[:find ?e])
        :where [?e ?a ?v]
      db)
```
To fix this, you'd have to adjust the indentation on all the subsequent lines manually (and auto-format isn't going to do the right thing because it can't know what you really want).

**Comment by patrickmesana** [comment]
+1

**Comment by pate** [comment]
How to use indent mode in Cursive?

**Comment by achikin** [comment]
@pate I came here with the same question. Looks like Cursive only implements indent mode, so switching Structural style to 'Parinfier' gives you intent mode.

**Comment by binarykitchen** [comment]
@cursive-ide is there a github ticket for the lite paren-mode? keen to subscribe to it ...

**Comment by Cka3** [comment]
@binarykitchen https://github.com/cursive-ide/cursive/issues/1303
