### ISSUE TITLE
Is is possible to compile a code region?

### ISSUE THREAD

**Issue by firebat** [cursive-ide/cursive#1222]
Just like Ctrl-c Ctrl-c in emacs with cider, so that the programmers could write a piece of code, compile the region and verify it in the REPL.

**Comment by cursive-ide** [comment]
I'm not sure what you mean by the region. `C-c C-c`  in Emacs seems to be the equivalent of *Tools->REPL->Send top form to REPL*, which will send the top level form around the caret to the REPL. If you have a current selection, it will send the selection instead of the top-level form. 

If that command is not what you require, please reopen and provide more detail.

**Comment by firebat** [comment]
@cursive-ide exactly what I need, thx.
