### ISSUE TITLE
Settings Repository with Cursive Licence

### ISSUE THREAD

**Issue by jnape** [cursive-ide/cursive#1291]
It seems like the Cursive Licence is stored as an xml file in the config/options directory in the Intellij dot directory, which wreaks havoc on teams where intellij settings are shared via the [settings repository plugin](https://plugins.jetbrains.com/plugin/7566?pr=idea). Either the same licence is shared across multiple machines -- which as far as I can tell is a violation of your licencing policy -- or we add the CursiveLicence.xml file to the .gitignore for the settings repository plugin and it gets blown away on each restart.

What should we do in this situation? Should we just share the same physical licence (we've already purchased the appropriate number of licences for our team, so we're not trying to rip you off), or do you have any plans of using some other mechanism other than CursiveLicence.xml in config/options for storage?

Thanks,
-John

**Comment by cursive-ide** [comment]
That's awkward, thanks for the heads up! I'll fix this for the next build (out in a couple of days). Sorry for the hassle, I hadn't thought at all about the repo plugin.

**Comment by cursive-ide** [comment]
This is fixed in the next build. The doc is a little sparse on how this works, but I've configured this config item to be unshareable. I don't think you'll need the `.gitignore` entry since the plugin will no longer try to commit that entry. You will probably need to delete the existing one from your repo. I've done some simple testing and I believe this is correct - let me know if you continue to have problems.

**Comment by jnape** [comment]
Thanks Colin, I'll try it out when I get the next build.

**Comment by jnape** [comment]
Confirmed this is fixed in version 1.2.1-2016.1.

**Comment by cursive-ide** [comment]
Great, thanks for letting me know.
