### ISSUE TITLE
Load file in REPL doesn't work for local REPL

### ISSUE THREAD

**Issue by pkozikow** [cursive-ide/cursive#1349]
The action does nothing on a local REPL (using nREPL in normal JVM process). Interestingly, it works fine with a remote REPL.

**Comment by cursive-ide** [comment]
I can't reproduce this, I just tried this using a Maven project and it works fine. Do you get anything in your logs when this occurs?

**Comment by pkozikow** [comment]
I don't see anything in the logs (~/Library/Logs/IntelliJIdea2016.1/idea.log). Any other place I should look?

**Comment by cursive-ide** [comment]
Actually, one other thing that occurred to me - when you configure the REPL you select a module which will be used for the classpath of the REPL. Are you loading code into that REPL from a different module?

**Comment by pkozikow** [comment]
Yes I am. I know all dependencies are met though since when I run an external REPL based on the same module it works.

**Comment by cursive-ide** [comment]
Ok, I suspect this is the problem. I added a filter because people were having issues with the Sync Files in REPL command - it would load files when they had been modified even if they were completely unrelated to the open REPL. They're now filtered by the module used to start the REPL. It hadn't occurred to me that this would also affect Load Files in REPL. 

I'm not sure what the best fix is here. The previous behaviour was pretty painful for some people, but this is clearly a problem for you. I could make a fix such that an explicit load command always loads irrespective of the filter, but it might then be confusing for a user who loaded a file, saw it correctly loaded, then modified it but didn't realise that a sync would not load those modifications.

Can you briefly describe why you're loading files from a module unrelated to the module of the REPL?

**Comment by pkozikow** [comment]
The use case is that I have a main production module with all the "real" code, which is used as the basis for the REPL, and then a scripts module where I have quick oneoffs and experiments that I run using code from the main module. It's essentially a way to avoid "polluting" the main module.

**Comment by danielcompton** [comment]
I have a two projects, a main project, and a checkout project. I can't load the files from the checkout project anymore.

**Comment by cursive-ide** [comment]
@danielcompton Is there a dependency between the two projects?

**Comment by cursive-ide** [comment]
@pkozikow As a workaround, could you make your scripts module depend on your main one (if it doesn't already) and then use that module to launch the REPL?

**Comment by danielcompton** [comment]
Yep, one depends on the other's snapshot version.

**Comment by pkozikow** [comment]
Yes, using the scripts module is a good workaround and I can confirm it works.

**Comment by cursive-ide** [comment]
Since this change fixes a real problem and there's a good workaround, I'm going to leave the new code in place. To avoid confusion, I've added a message when someone tries to load a file into a REPL whose module isn't related:

![screen shot 2016-04-20 at 3 14 17 pm](https://cloud.githubusercontent.com/assets/5589171/14662475/a0208d22-070a-11e6-90dc-e71f182d75d5.png)

**Comment by danielcompton** [comment]
I ran into this again recently. I'd added a project as a checkout, and Cursive had recognised it, but I still needed to open the checkout projects `project.clj` and click "Add Project" in the header for Cursive to allow me to load it from the REPL.
