### ISSUE TITLE
Can't run main method

### ISSUE THREAD

**Issue by winteryoung** [cursive-ide/cursive#1355]
# Env

IDEA 2016.1.1
Leiningen 2.6.1 on Java 1.8.0_60 Java HotSpot(TM) 64-Bit Server VM
# Steps to reproduce
1. Create an empty lein project via `lein new app clojure-test`
2. Run the generated hello world main method. No hello world shown.

**Comment by perryprog** [comment]
Are you running it like "right click > run 'core'" or are you going into Leiningen > run?
The only reason it might not be running is because leiningen runs the -main function automatically. (Like `public static void main` in java) and running the clojure file by itself won't do anything.

Some things you can try to do to make it run:

* Look for anything that says "Leiningen" depending on whether you use Inteliji or Eclipse or what have you, this will be different, but you should somewhere see a place where you can click. In Inteliji it's Leiningen (on the right side) > closure-testxxx > Tasks > Run
* In Inteliji next to the Make project button there is an arrow that you can click. Click it, and then hit "Edit configuration". Hit CMD/CTRL + N and type in "lein" hit enter and follow the instructions from there.

**Comment by seanf** [comment]
I'm in a similar boat with an empty lein project. The Leiningen view only shows these tasks (no `run`): pom help upgrade install jar deps uberjar test clean compile version.

This helps: http://stackoverflow.com/a/37446830/14379

It's a small thing, but in terms of first-time user experience, it would really help if Cursive could interpret "running a project" the way lein does, perhaps only when right-clicking on the project (right next to Run REPL for my-project).

**Comment by aliaksei-lithium** [comment]
We defiantly need easy way to run Clojure program with one click. Current solution with leiningen not obvious. 
And also suggest not mark `(defn -main)` as unused function.
