### ISSUE TITLE
Provide changelog

### ISSUE THREAD

**Issue by a613** [cursive-ide/cursive#1389]
The text shown by IntelliJ when it finds a Cursive update has no information on what changes are included. Further, there is no place online (at least indexed by Google) that lists a changelog either.

The update text should at a minimum include a link to an online changelog, if not list everything directly.

<img width="967" alt="screen shot 2016-05-03 at 4 15 56 pm" src="https://cloud.githubusercontent.com/assets/5733420/14996978/865b9a18-114a-11e6-9b66-b7cff55f1823.png">

**Comment by bilekt3** [comment]
Cursive changeling is announced via mailing list - https://cursive-ide.com/archive/ (i.e.: https://cursive-ide.com/archive/1956.html)

**Comment by abhin4v** [comment]
The archive links give 404 Not Found.

**Comment by cursive-ide** [comment]
Yes, the mailing list has been migrated to a Google group [here](https://groups.google.com/forum/#!forum/cursive). I'll see if I can redirect /archive/* but it won't redirect to the correct message.

**Comment by hairybreeches** [comment]
This issue is really important.

Without release notes (and neither of the links above seem to take me to anywhere I can actually read them), there's no way to find out what new features are being added and start using them.

My update subscription expired recently. I hadn't had any response on the issues I'd filed, so when it came time to renew, I went looking for what else had been added/fixed over the last 12 months. You've probably been really busy and added loads of awesome stuff in that time, but I've got no idea what any of it is, so it's pretty hard to justify shelling out for another 12 months.

**Comment by cursive-ide** [comment]
I have finally fixed this. My apologies for the ridiculous amount of time it took me to get to this. The changelog can be found [here](https://github.com/cursive-ide/cursive/blob/master/CHANGELOG.md). For now I've included the link in the plugin description within the IDE, and I will figure out the best way to generate the changelog content into the description as well.
