### ISSUE TITLE
Add compatibility with IntelliJ IDEA 2016.2

### ISSUE THREAD

**Issue by extesy** [cursive-ide/cursive#1407]
https://confluence.jetbrains.com/display/IDEADEV/IDEA+2016.2+EAP

**Comment by flaminc** [comment]
I saw Colin mention the time frame on this in the mailing list archives [here](https://cursive-ide.com/archive/1983.html) saying 'hopefully ... next week'.

**Comment by extesy** [comment]
@cursive-ide Colin, when do you think it would be possible for you to add 2016.2 support?

**Comment by cursive-ide** [comment]
It should be early next week. I was hoping to get a couple of bug fixes into the same release but they are proving much more complicated than expected so if I can't fix them on Monday I'll bump them to the following build.

**Comment by cursive-ide** [comment]
This is fixed in 1.3.0-eap2.

**Comment by torbjornvatn** [comment]
How do I install 1.3.0-eap2? I can't find it in the plugins settings

**Comment by cursive-ide** [comment]
@torbjornvatn This is tricky if you don't already have Cursive installed because it's an EAP release - sorry. Go to *Settings&rarr;Plugins&rarr;Browse Repositories...&rarr;Manage repositories...*. Add a repository with the URL `https://plugins.jetbrains.com/plugins/eap/8090`. Go back to the *Browse Repositories* panel, refresh and then you should see the right version of Cursive.

**Comment by torbjornvatn** [comment]
Nice!

**Comment by decadent** [comment]
To anyone trying to install the EAP: after adding the repo, you have to actually select it in the 'Browse repositories' dialog, in the dropbox at the top. Otherwise you won't see Cursive EAP in the list.
