### ISSUE TITLE
Cannot generate stubs when using figwheel-sidecar v0.5.4+

### ISSUE THREAD

**Issue by awkay** [cursive-ide/cursive#1532]
I'm using IntelliJ 2016.2 and Cursive 1.4.0-eap2-2016.2

The following open-source project will demonstrate the error (claims to have an invalid figwheel config):

https://github.com/untangled-web/om-css

If I downgrade to 0.5.3 it can generate stubs.

**Comment by cursive-ide** [comment]
This is a problem in the `dev/user.clj` file. The `(def figwheel-config (fig/fetch-config))` is side-effecting and causes Figwheel to be loaded and to try to validate the project.clj file. The figwheel validation fails because the process that Cursive uses to generate the stubs doesn't have the project root set as the CWD (in general, it can't because the stub generation can be used for multiple projects at once in a multi-module project).

The same problem exists in https://github.com/awkay/untangled-template-workspace, which I was just looking at with another user.

I'd like to provide a better error message for this, but I'm not sure how to. I don't think this is a Cursive bug since there's nothing I can do to fix it, so I'm going to close this.

**Comment by awkay** [comment]
Hey Colin, Thanks so much for looking into that. We'll fix the template and such. Appreciate the help.
