### ISSUE TITLE
1.4.0-eap3 fails when importing multi module projects with :version

### ISSUE THREAD

**Issue by lkonstantinov** [cursive-ide/cursive#1548]
When trying to import a lein-modules project, Cursive now fails with:

```
java.lang.IllegalArgumentException: No value supplied for key: :version, compiling:(C:\work\git\playground\clj-hub\domains\project.clj:1:1)
					No value supplied for key: :version
```

where it used to work with 1.4.0-eap2.

The child module project dependencies definition looks like this (using both parent and dependency version resolution):

```
  :dependencies [
                 [com.tick42.hub/authentication :version]

                 [com.taoensso/timbre "_"]
                 ]
```

**Comment by lkonstantinov** [comment]
Probably related to this: https://github.com/technomancy/leiningen/issues/2212

**Comment by cprice404** [comment]
Yeah, almost certainly related to that lein issue.  We have a fix for that but it won't be out until lein 2.7.2.  I wonder if a user could select an older version of lein from the Cursive dropdown until lein 2.7.2 is available.

**Comment by cursive-ide** [comment]
Ok, it looks like this is a problem with lein 2.7.1. You will have started seeing this in 1.4.0-eap3 because I added 2.7.1 to the list of available versions there, and Cursive by default uses the most recent version. Selecting 2.7.0 in *Settings->Build, Execution, Deployment->Build Tools->Leiningen->Project Settings* should hopefully work around the issue.

I'm going to close this since it does not appear to be an issue with Cursive.
