### ISSUE TITLE
Bizzare string concat issue with Cursive + nrepl

### ISSUE THREAD

**Issue by halgari** [cursive-ide/cursive#1565]
The following code:
```clojure
(.concat (.concat "\n" "     ") "hi")
```

Returns `"\nhi"` on Cursive's repl when used with either of the nrepl options. Works fine (prints `"\n<space><space><space><space>hi"`) when used with the clojure.main repl in Cursive, or when nrepl is used with emacs.

**Comment by levand** [comment]
This also manifests in more idiomatic code.

```
(apply str "a" "\n" "  " "hi")
=> "a\nhi"
```

Expected result:
```
(apply str "a" "\n" "  " "hi")
=> "a\n  hi"
```

It also occurs in code that is sent to the REPL, including inside of function definitions, which is quite annoying and mysterious.

**Comment by cursive-ide** [comment]
This is indeed not what you'd expect. This is actually a feature that sounded like a good idea at the time, but is not - see #1183, which also describes how to turn this off. In a comment on that issue, I said I was going to fix it but that actually turns out to be hard because fipp (which does the pretty-printing) is incremental and I can't tell when printing a string if there's going to be more output which will cause a line to be broken.

It's actually a very useful feature when working with large data structures containing multi-line strings, but it's so confusing in this case that I think I'll have to remove it. Anyway, I'll close this issue since it's being tracked in the other one.
