### ISSUE TITLE
lein working directory when importing project dependent on where idea is launched from

### ISSUE THREAD

**Issue by joekiller** [cursive-ide/cursive#1606]
I am trying to use a project that dynamically sets the version number. I created a sample project here: 
https://github.com/joekiller/lien-git-version-blank

If you open Intellij in the project directory and import, everything goes fine.

But if I open Intellij from anywhere else, I get the error:
 > 12:15 PM	Error reading /home/jlawson/public/lien-git-version-blank/project.clj: src/lien_git_version_blank/version.clj (No such file or directory)

It seems like Leiningen's validation isn't using the project root directory as it's current working directory.

**Comment by cursive-ide** [comment]
So... right. This won't work, because of the way that the `lein-git-version` plugin works.

The long version is that Cursive executes lein in-process using a complicated mechanism. This is because many users have large multi-module projects. The JVM doesn't provide a means to change the CWD of the JVM process, so Cursive tries to fake it - it works well for 99% of cases, but not for this one. The `lein-git-version` plugin uses `sh` to execute git, and it assumes it's in the right directory.

Unfortunately the only way to support this accurately would be to spin up a new JVM for each lein module for each sync, which would be unworkably slow. Unfortunately this is unlikely to ever be supported.

**Comment by joekiller** [comment]
Thanks for the feedback!

-Joe
Sent via mobile.
