### ISSUE TITLE
How to disable Cursive's word highlighting?

### ISSUE THREAD

**Issue by salmazov** [cursive-ide/cursive#1663]
![_13 2 2017_ _21_38_24](https://cloud.githubusercontent.com/assets/1635615/22918144/e184ba56-f299-11e6-8214-7aa3acbc1b1a.png)

I don't know about other developers, but for me this colourful hightlighting celebration is annoying. How to disable it?

Looks like I select multiple parts of my code.

And Sublime Text (that's looks good!):
![default](https://cloud.githubusercontent.com/assets/1635615/22918213/46d5401a-f29a-11e6-8a4d-85044faa55f3.PNG)

How can I set up Cursive to similar settings?

**Comment by cursive-ide** [comment]
That highlighting is because Cursive doesn't know how to resolve those symbols. I'm not sure what that macro form is, but Cursive has problems resolving symbols defined in macros. If you don't want those warnings (they can be annoying if you're working with macro libs that Cursive doesn't understand) you can turn them off at *Settings&rarr;Languages & Frameworks&rarr;Clojure&rarr;Highlight unused symbols*.

**Comment by cursive-ide** [comment]
I'm going to close this.

**Comment by salmazov** [comment]
![_16 2 2017_ _23_13_02](https://cloud.githubusercontent.com/assets/1635615/23055056/b27d3b5e-f4f4-11e6-8ef8-f7a64a23b3ff.png)
Where is the unused symbols?
