### ISSUE TITLE
"Resolve as" intention not available

### ISSUE THREAD

**Issue by lkonstantinov** [cursive-ide/cursive#1666]
For some reason I can't get the "Resolve as" intention to even appear using Cursive 1.4.3-2017.1

<img width="419" alt="no_resolve" src="https://cloud.githubusercontent.com/assets/3921426/23204460/570c3dde-f8ef-11e6-8305-7f188898bb1f.png">

**Comment by metametadata** [comment]
Can confirm,  v1.5.1-eap1-2017.1.

**Comment by cursive-ide** [comment]
When a few people have had this recently, it's been because the intention was disabled for some reason. Could either of you confirm if this is the problem in your case?

![screen shot 2017-09-05 at 09 48 39](https://user-images.githubusercontent.com/5589171/30039035-a826bbbc-921f-11e7-8846-208335a67342.png)

**Comment by metametadata** [comment]
Yes, it is disabled! Enabling it fixes the issue.

**Comment by cursive-ide** [comment]
@metametadata Great, thanks for letting me know! Sorry I forgot to update this issue when I discovered this a while ago.

**Comment by cursive-ide** [comment]
I'll close this issue for now, if this is a problem for anyone and the intention is enabled, feel free to reopen it.
