### ISSUE TITLE
Add additional substitutions for REPL commands

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#1694]
Some that seem potentially useful:

* `selected-form`, which is only valid if a valid Clojure form is selected (`selection` will accept anything right now).
* `file-name`
* `file-path`
* `file-namespace`

**Comment by thheller** [comment]
- test-under-caret (qualified-symbol with name of test)

So that we can easily emulate the `Run test under caret in REPL` action within a non-nREPL.

It would be neat if we could emulate any other built-in REPL command but add additional things to it. Something like `Sync files in REPL` would be nice to have as I usually want to run something before and after syncing. I currently use tools.namespace for that instead of Cursive sync but sometimes that is overkill.

**Comment by cursive-ide** [comment]
Good idea - in fact things like "currently selected editor var" seem like they might be generally useful, see #1696.

**Comment by cursive-ide** [comment]
Some other useful ones would be `form-before-caret` and `top-level-form`, to allow commands which mimic the built-in REPL evaluation commands, as suggested above.

**Comment by cursive-ide** [comment]
I guess also that the REPL command should be disabled if substitutions that it requires are not available.
