### ISSUE TITLE
Modules cannot be added correctly from the Project Structure view

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#1729]
After importing, the modules don't appear in the UI, and the UI can show a lot of spurious errors since its state is not correctly updated after the sync.

**Comment by onetom** [comment]
I would like to avoid polluting source repos (and .gitignore files) with IntelliJ/Cursive related files, simply because it irritates some people on the same project who are not using IntelliJ.

It seems IntelliJ supports storing `.idea` and `*.iml` files outside of the project root.
I would be willing to put up separately distributing these project files via a separate git repo
or just by rsync-ing it amongst my machines until I'm the only Cursive user on the project.

However this feature doesn't work consistently.

*Project Structure / Modules / Add (+) / New Module / Leiningen / [Next]* dialog has two separate fields:

* Content root
* Module file location

If I change the _Module file location_, a `module.iml` will be correctly created in the specified directory, instead of the Content root (where the `project.clj` and the rest of the source code lives).

The *Project Structure / Modules* list updates correctly too, just as well the Project tree view and the Leiningen panel's list of modules.

BUT if I choose *Project Structure / Modules / Add (+) / Import Module*, then either I pick the `project.clj`
or just the directory containing the `project.clj`, then select *Import module from external model: Leiningen* the following dialog only contains

* Root Directory
* Keep project files in

fields, no _Content root_ and _Module file location_.

**Comment by cursive-ide** [comment]
@onetom I've filed #1744 for that.
