### ISSUE TITLE
Macroexpansion's notion of "current expression" is confusing/inconsistent

### ISSUE THREAD

**Issue by cemerick** [cursive-ide/cursive#1739]
The notion of "current expression" in lisp editors, AFAIK, is consistently the form just prior to the cursor's position. Evaluating the "current expression" with the cursor in various positions shakes out like so:

```
(+ 1 5)|   => 6
(+ 1 5|)   => 5
(+ 1| 5)   => 1
```

Cursive follows this convention, too…_except_ when it comes to macroexpansion. Despite hints from Colin, I still can't quite figure out the rules it uses to determine "current expression". Some examples of current behaviour:

Expression + cursor position | "current expression"
-----------------|-------------
`(if-not (< 1 2) 6)\|` |    The expression _after_ the `if-not`
`(if-not (< 1 2) 6\|)` or `(if-not (< 1 2)\| 6)` or `(if-n\|ot (< 1 2) 6)` |    the `if-not`
`(if-not \|(< 1 2) 6)` or `(if-not\| (< 1 2) 6)` |    `(< 1 2)`
`(for [a (range 6)] \|(if-not (< 1 2) 6))` | `if-not`
`(for \|[a (range 6)] (if-not (< 1 2) 6))` | `for`

Based on this, I can't infer what rules are in play (nevermind be able to know confidently where to put the cursor to do a macroexpansion "in the fog of editing"). Maybe there's some bug(s) complicating the results above, maybe cursive is relying on intellij's AST in some non-obvious way, I dunno.

I'd obviously prefer that macroexpansion's notion of "current expression" simply be same simple rule as that used for REPL evaluation; short of that however, help?

**Comment by cursive-ide** [comment]
So I'm on the fence about this. The *intention* was that the expansion be for the innermost form enclosing the caret which is a macro invocation. That seems buggy looking at your examples, in particular the third and fourth ones are clearly wrong, I'll fix those.

I think the notion for REPL evaluation that the form you evaluate is the one before point is fairly specific to that use case, because in a lot of cases you've just written the form you want to evaluate. That's not the case with macroexpansion, and making the user put the caret in essentially one single point rather than just anywhere inside it seems unnecessarily fiddly. To support my argument, [here's](https://www.youtube.com/watch?v=aYA4AAjLfT0#t=48m07s) a video I just watched of Bozhidar demoing the macroexpander in CIDER where he forgets that he has to put the caret at the end of the form, and puts it anywhere inside the form instead - that's clearly his immediate intuition about how it should work.

**Comment by cemerick** [comment]
Okay, I'll reserve further judgement on the cursor position until those fixes land.

Now though, I think I know why I struggled for so long to get the macroexpansion popup to show at all:

1. I was probably putting the cursor within a non-macro form, attempting to macroexpand the _prior_ form.
2. Since the macroexpansion action isn't active unless its notion of current-expression is a macro, well, nothing was happening.

It seems like intellij should issue a system ding when a disabled action is attempted, but maybe not…

**Comment by cursive-ide** [comment]
This has been fixed in the latest build, out now. Cursive will now pick either the form immediately before the caret if that's a macro, or the innermost form surrounding the caret which is a macro/expandable thing. This should hopefully be consistent.
