### ISSUE TITLE
Attempts alias symbol resolution

### ISSUE THREAD

**Issue by mfikes** [cursive-ide/cursive#1747]
In Cursive 1.5.0-2017.1, namespace aliases established for core ClojureScript namespaces are marked as "cannot be resolved". (Note that this does not appear to occur with aliases for in-project namespaces.)

Minimal repro:

`project.clj`:

```
(defproject foo "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [org.clojure/clojurescript "1.9.521"]])
```

`src/foo/core.cljs`:

```
(ns foo.core
  (:require [clojure.string :as bar]))
```

The symbol `bar` above will be marked with "bar cannot be resolved".

**Comment by mfikes** [comment]
I found that this does not repo for me on another box. So, I solved the issue by moving `~/Library/Caches/IntelliJIdea2017.1/index/clojure*` to another location and re-opening the project to let it re-index.

One theory could be that the index was somehow corrupted (this occurred on a dual hexacore Mac and it appears to use all of the cores while indexing—perhaps therefore more susceptible to any threading bugs). I tried putting the old "bad" indexes back to try to see if that allows reproducing again, but that fails (it appears to re-index anyway). I've tried removing the indexes several times and opening a more complex project to try to provoke a subsequent failure and have been unable to do so.

I still have the original index files if you think they might help, Colin. It is up to you—I'm certainly OK if this issue is closed as not reproducible if you'd like.

**Comment by cursive-ide** [comment]
Yes, I think I'll close this. The indexes do tend to get corrupted from time to time, and that seems to be bugs at the IntelliJ layer. Cursive provokes them more than, say, the Java support, probably because it uses them in unusual ways. But even in stock IntelliJ it happens often enough that there's a dedicated action to force a re-index: *File&rarr;Invalidate Caches & Restart*.

The index files won't mean much to me since they're in IntelliJ's binary format, so I think I'll just close this.
