### ISSUE TITLE
'find usages' of keyword is inefficient for keywords with frequent name part

### ISSUE THREAD

**Issue by vvvvalvalval** [cursive-ide/cursive#1767]
I have found that, for some keywords with a common name part such as `:person/name` and `:client/id`, 'find usages' is slow (several seconds), whereas it's fast on keywords like `:person_name` and `:client_id`.

My suspicion is that only the name part is indexed. Could this be made faster by indexing the whole keyword?

Cheers,

Val

**Comment by cursive-ide** [comment]
I think this is just a side-effect of how IntelliJ indexes and resolves references. Keywords are actually indexed with the namespace. However when searching for a use of a namespaced keyword, you have to search using only the name part because you might find forms like `::keyword`, `::alias/keyword`, `:name.space/keyword`, `#:alias{:keyword ...}` etc etc. 

When IntelliJ searches, it uses a very fast word index initially to find all usages of the name of whatever you're searching for. It then resolves each of those to see if it's actually a reference that points to the thing you're searching for. I'm not sure that I can make this much faster without some serious indexing trickery.

I'm going to close this one, since I don't think there's a useful fix that I can make.

**Comment by cursive-ide** [comment]
Actually, I'm going to reopen this, looking at the code there is one improvement I think I can make. I'm not sure how much difference it will actually make, perhaps some.

**Comment by cursive-ide** [comment]
I made some changes here, since some of the Cursive word indexing was making an obsolete assumption. This improves index efficiency somewhat, but I don't think it will increase the speed in the case you mention - I think this is just how IntelliJ works, unfortunately.
