### ISSUE TITLE
After latest update can't open recent files tab.

### ISSUE THREAD

**Issue by ertugrulcetin** [cursive-ide/cursive#1782]
One of the errors: 

`clojure.lang.PersistentHashMap cannot be cast to com.intellij.psi.PsiElement`
also getting **index** exceptions...

**Comment by cursive-ide** [comment]
1.5.2 was bad due to a bad merge before the release, causing the builds for some IntelliJ versions to contain incomplete changes intended for 1.6.0. There's a message on the [mailing list](https://groups.google.com/d/msg/cursive/4xlDyyteirw/3_q8Dyp9CwAJ) about this containing instructions for how to downgrade to 1.5.1.
