### ISSUE TITLE
Cursive confuses projects because it ignores namespace

### ISSUE THREAD

**Issue by vincent-dm** [cursive-ide/cursive#1834]
My current IntelliJ project is a big "monorepo" of multiple interacting apps which each have their own `project.clj` file. Thanks to Cursive's `Leiningen` tab I can easily specify where the projects live and get sane highlighting etc.

However, I am currently experiencing problems due to two projects having a similar name:
1. `apps.collectors/backend`
2. `apps.datastore/backend`

I was able to add both projects in the `Leiningen` tab, but there are several problems:
* Folders of the second project are not highlighted as such in the Intellij project window.
* When I open the second project's `project.clj` file I get the alert "_File project.clj is not under a source root_".
* The second project is not listed in the modules drop-down when creating a REPL configuration.

So it seems that Cursive somehow confuses both projects due to their similar naming. I think it is quite common to have multiple projects called "_frontend_", "_backend_", etc. Therefore I propose to take the full (namespaced) project name into account and not just the part after the slash.

Thank you!

**Comment by cursive-ide** [comment]
I've just spent some time looking into this, and the problem is indeed as you suspected. It's actually an IntelliJ problem rather than an issue for Cursive - the issue is that IntelliJ will not allow more than one module with the same name within a single IntelliJ project. The module name is always taken from the module file name, so its name has to use characters valid in cross-platform filenames (so `apps.collectors/backend` is not a valid name). I think the best option would probably be `apps.collectors.backend`.

However this is a *very* high-impact change - everyone who has a lein project with a qualified project name will have their module names changed and I'd need to do some analysis on the impact of that. It's possible existing projects wouldn't actually be touched but I need to think it through properly and test it. I had this change slated for the next EAP but I think that's probably unlikely.

**Comment by vincent-dm** [comment]
Thanks @cursive-ide  for looking into this.

I can see that a fix would be high impact, but I guess that will only get worse as the user base grows?

As the famous Phil Karlton quote goes "_There are only two hard things in Computer Science: cache invalidation and naming things._".

This issue complects the already hard challenge of naming things, so as far as I'm concerned it is worth fixing :-)

**Comment by vincent-dm** [comment]
Ok, it seems that the solution you propose (dropping the namespace and using only dots as separators) does work properly.

I initially interpreted your suggestion as the to-be implementation of your fix, but I'm glad to see it already offers a workaround if I rename the projects myself. Thanks!
