### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by ooronning** [cursive-ide/cursive#1859]
Hi there.

I was excited to download Cursive today, and while it is clearly a well-made tool, there are some issues that I'm having trouble getting around.  I also see that there are 790 open Issues at the moment, and no code in the repo, so it's not like I can personally confirm when the last code was committed.

Unfortunately, it's looking like alot of fundamental Clojure tools have just been more or less abandoned. This and Light Table, the only two good Clojure editors I can find, seem to have no maintainers, and since I'm not really willing to learn Emacs just so I can do some basic learning projects, I'll probably end up abandoning the language. 

Am I wrong? Is this IDE maintained?

**Comment by pbaille** [comment]
Yes it is maintained, but closed source.

**Comment by cursive-ide** [comment]
Right, it's an actively maintained plugin, but it's closed source and commercial (although free for non-commercial work like personal projects). 

I'm going to close this since it's not an issue as such - if you have more questions, the [mailing list](https://groups.google.com/forum/#!forum/cursive) is probably the best place.
