### ISSUE TITLE
Feature Request: Named REPLs

### ISSUE THREAD

**Issue by conan** [cursive-ide/cursive#1974]
I often have several REPLs running at once, and always at least two (clj and cljs).  The names of the REPL tabs show the current namespace, e.g `Local: user`, but I often have the same namespace in multiple REPLs (especially that `user` one).  It would be really useful if I could add a name to each one so I could distinguish between clj/cljs and different projects.  

For example, I'd love to have tabs named `Local - clj - myproject - user`.  Even better would be if they could simply be colour-coded (or stripey or something) to distinguish clj/cljs, and contain the project name otherwise: `Local - myproject - user`.  That might not be ideal for projects containing multiple builds though.

**Comment by msolli** [comment]
I have several run configuration for running REPLs (over an SSH tunnel) to different environments (see screenshots). It would be awesome to be able to set the name of the REPL in the run config, so that I can see from the tab title which REPL I'm in when there are several open at the same time. There are things I do locally that I wouldn't necessarily do in production, for instance.

<img width="182" alt="Screenshot 2019-04-30 13 45 59" src="https://user-images.githubusercontent.com/70058/56959626-50e02a00-6b4e-11e9-9f9d-34d56421698b.png">
