### ISSUE TITLE
Install fails with Goland IDE

### ISSUE THREAD

**Issue by dnephin** [cursive-ide/cursive#1987]
According to https://plugins.jetbrains.com/plugin/8090-cursive cursive should be compatible with Goland, however I'm not able to install it.

IDE Version:
GoLand 2018.1.2
Build #GO-181.4668.90, built on April 26, 2018

When I search for it under "browse repositories" it does not show up. I tried adding the EAP repo as well (still nothing).

Next I tried to download the zip (1.6.3-2018.1) and install it from disk. In the log I got the following error:

```
Plugin 'Cursive' can't be loaded because: Plugin does not include any module dependency tags in its plugin.xml therefore is assumed legacy and can be loaded only in IntelliJ IDEA
```

I found this [doc about plugin compatibility](http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/plugin_compatibility.html). I unzipped the archive and added this to the plugin.xml:
```
<depends>com.intellij.modules.lang</depends>
```

which caused:

Caused by: java.lang.ClassNotFoundException: com.intellij.openapi.actionSystem.DataKeys PluginClassLoader[com.cursiveclojure.cursive, 1.6.3-2018.1] com.intellij.ide.plugins.cl.PluginClassLoader@5d2a95cc

According to [this support issue](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206767135-DataKeys-class-not-found-in-PhpStorm) it might be possible to use LangDataKeys or PlatformDataKeys instead.

Should  the plugin description be updated to reflect the plugin only works with IDEA, or do you think it would be possible to make it work with Goland?

Thanks!

**Comment by cursive-ide** [comment]
Hmm, Cursive is currently only compatible with IntelliJ, because it relies on the IntelliJ Java support which isn't available in the other IDEs. JetBrains were working on making the Java support a true plugin, currently it's somewhat blessed in IntelliJ for historical reasons, but I'm not sure how that's going. I'm not sure why the repo is showing Cursive as compatible with the other IDEs, I'll contact JetBrains about that.

**Comment by dnephin** [comment]
Thanks
