### ISSUE TITLE
Adding a (Java) dependency to project.clj adds only the binary classes artifact, not the sources

### ISSUE THREAD

**Issue by hlship** [cursive-ide/cursive#201]
Within IntelliJ I'm used to adding a dependency to my build script (in Gradle or Maven) and having the dependency's binary artifact added to the classpath but also having the source for the artifact downloaded and attached to the binary artifact.

This doesn't seem to happen with the Leiningen support; changing project.clj and clicking the refresh button in the Leiningen tool window adds the new dependency, but there's no source attachement.

**Comment by pmoriarty** [comment]
This seems to have regressed. I'm not seeing sources being downloaded automatically. The "Download Sources" link at the top of the editor works fine but I have to do that manually for each dependency.

Tested using the following minimal project.clj:

```
(defproject leintest "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [org.yaml/snakeyaml "1.12"]
                 ])
```

**Comment by cursive-ide** [comment]
This hasn't worked since Jan 2014 :-)

I took this out deliberately and removed the config items that controlled it. The issue is that downloading sources automatically is a bad idea in Clojure projects because the majority of libs don’t have sources, so every time you refresh (which is every time you start up, plus more) it will go to every repo, for every lib that it hasn’t managed to download sources, for every lein module in your project. It made synchronising agonisingly slow. I'm open to suggestions for how this might be configured - I'm not sure if metadata on the dep vector could be an option, but that will only be for top level deps, not transitive ones.

**Comment by pmoriarty** [comment]
I usually work with Gradle so didn't notice! Even a button or menu option to manually trigger a download of all sources would be fine for me.
