### ISSUE TITLE
feature request: display javadoc

### ISSUE THREAD

**Issue by marco-m** [cursive-ide/cursive#2014]
Hello, thanks for Cursive! :-)

Consider the following snippet, taken from https://clojure.org/guides/repl/data_visualization_at_the_repl:

```clojure
(require '[clojure.java.javadoc :as jdoc])
(def v (io/input-stream "https://www.clojure.org/"))
(jdoc/javadoc v)
```

when executing `(jdoc/javadoc v)`, a browser will open on the javadoc for BufferedInputStream.

Cursive already has the very handy "Quick documentation" with Ctrl Q (Ctrl J); it would be nice to support also showing the Javadoc when available. At least looking https://cursive-ide.com/userguide/documentation.html I don't think that Cursive supports it.

**Comment by cursive-ide** [comment]
You're welcome :-)

Cursive does support showing the Javadoc, but to do that requires something which resolves to a class, method etc. So if you have a usage of BufferedInputStream in your code and you use the quick doc function, it will work there. What Cursive can't do is the runtime invocation of it from the REPL since that would require the REPL to send commands back to the IDE. I have some ideas along those lines, but there's nothing in there yet.

**Comment by marco-m** [comment]
I was confused, you are right, the Javadoc is already shown. thanks!
