### ISSUE TITLE
Large test result previews don't display

### ISSUE THREAD

**Issue by conan** [cursive-ide/cursive#2032]
When my `deftest` tests fail, Cursive often can't show the results.  Instead of popping up the overlay with the test results when I hover over the `is` form, the cursor rapidly switches back and forth between a hand and an arrow, and the results are never displayed. This seems to happen when testing function specs using `clojure.spec.test.alpha/check` using inputs with large amounts of spec, which are therefore generating large diffs between the values.

I'm not able to find a small reproduction, but here's the test infrastructure:

```
(defn check
  "Passes sym to stest/check with a :max-size option of 3 (i.e. generated sequences will have no more than 3 elements,
   returning true if the test passes or the explained error if not"
  [sym]
  (-> (stest/check sym {:clojure.spec.test.check/opts {:max-size 3}})
      first ;; stest/check accepts a variable number of syms, this does not
      :clojure.spec.test.check/ret
      :result))

;; a function with args and ret specs
(defn a-fn
  [a b]
  ...
  )

(s/fdef a-fn
  :args (s/cat :a :something/big :b :something/bigger)
  :ret :something/huge)

;; at test
(deftest a-fn-test
  (is (true? (check `a-fn))))
```
I've done it this way so I can exercise my function specs, getting either a true result or the error displayed.  Problem is, Cursive won't display the error except in trivial cases.  I'm sorry I can't create a short reproduction, I think the issue is related to the length of the preview output; a stack trace is usually fine (although sometimes I get the flicker for a few seconds before the preview appears), but a large generated spec diff always fails.

I seem to recall that pointing at the exclamation mark in the left margin would previously show the diff, but that no longer seems to happen so I have to point at the `is` form, which is where I experience this problem.

__Update:__ I just noticed that pointing to the little red line in the margin near the scroll bar displays the results correctly, although it doesn't give me a link to view the diff when viewing it that way.  There is a scroll bar in the popup to navigate the output, but I can't figure out how I would use it because if I move the mouse then the preview disappears, and any keypress also makes it disappear.

**Comment by conan** [comment]
Even just getting the results printed to the REPL would be great

**Comment by conan** [comment]
It's possible the problem occurs when the preview won't fit on the screen, but hard to confirm

**Comment by marco-m** [comment]
I saw the same behavior on various Cursive versions.

**Comment by conan** [comment]
I'm pretty sure this is entirely down to the error not fitting on the screen, but given lots of our tests are generative ones for fairly complex specs, this happens often

**Comment by cursive-ide** [comment]
Yes, I think that's correct. Do you have a suggestion for what you'd like to see in the tooltip in cases where the output is bigger than some limit? Something like the number of keys with differences or similar?

**Comment by hannahhenderson** [comment]
I've experienced a similar issue several times. When I hover over a test error, the preview appears, but there's no way to expand it. The `Show difference` link isn't visible, and there's no way to mouse over to the link.

I'm not sure if `Show difference` is unavailable because the error is so large that Cursive can't actually show the difference, or if it's because the formatting of the error somehow hides the link. When I hover over the error, it flickers in a way similar to when pixels are off on a website scroll, and the whole active component flickers.

In general, if I could put my cursor into a failed test and use some sort of keyboard shortcut to "show difference" of that failed test, I would greatly appreciate that functionality. For me, it would side-step the flickering issue, and the careful mouse-drag I currently perform to click on `Show difference` when an error occurs.

**Comment by conan** [comment]
In the case that it won't fit on the screen, i'd like a scroll bar - it essential always to see the error.  Some other way of viewing the diff would also work fine, i'm not attached to tooltips.
