### ISSUE TITLE
environment variables defined using environ.core are not propagated to program when using trampoline

### ISSUE THREAD

**Issue by joelmarty** [cursive-ide/cursive#2050]
use case:
in my project.clj, I use environ lib (1.1.0) and I have the following:
```clojure
{
  :profiles {
    :dev {
      :env {
        :port "8080"
      }
    }
  }
}
```

then I start my app using a leiningen "run" run configuration, with the +dev profile and trampoline enabled. Single instance and Share options are turned off and no other action is configured.

what happens: (:port env) is nil. ex:
```clojure
(ns my-ns
  (:require [environ.core :refer env]))
(println "starting on port " (:port env))
```
which prints "starting on port nil"
Disabling trampoline resolves the issue, but then I can't debug.
Putting a breakpoint on the line and inspecting the "env" var yields the same as running "env" in a terminal but none of the variables defined in the :env map

expected: the code prints "starting on port 8080"

**Comment by cursive-ide** [comment]
This is fixed for the next EAP. There's one case where this doesn't work, which is running a Clojure script using lein. Running a main function from a specified namespace does work, however. 

This is due to the details of how environ works - it creates a hook which is executed when lein calls a task, but Cursive internally doesn't do that when executing a script because there's no lein task which permits that (the lein-exec plugin does, but it's not available by default). So this will work for most cases - I can probably do some awful environ-specific hack if that turns out to be an essential use case for someone, but I'd rather not do it unless required.
