### ISSUE TITLE
Certificate defined in project.clj not found in project root

### ISSUE THREAD

**Issue by RobotLimeLtd** [cursive-ide/cursive#2067]
I need to connect to an internal corporate Nexus server that uses an internally-signed SSL certificate.  I've added the signing certificate PEM into the root of my project, and then defined in my project.lcj file as follows:

:certificates ["mycert.pem"] 

This works fine when running from the command line, but the Cursive plugin in IntelliJ complains it can't find the certificate.  If I put in the full path to the certificate, then it works, but obviously this is not desirable for a project shared over source control.

Where does Cursive search by default, if a full path is not given?

**Comment by cursive-ide** [comment]
Which Cursive version are you using? This was fixed recently in #1156, but that fix is still only available in the current EAP (since eap4), not the stable build. If you'd like to receive EAP builds, see [here](https://cursive-ide.com/userguide/index.html#eap).

I'll close this since it's essentially a duplicate.
