### ISSUE TITLE
Upgrade nREPL

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#2102]
The nREPL bundled with Cursive should be upgraded to the new nREPL.

**Comment by d-t-w** [comment]
Leaving a note for fellow travellers.

Had an issue where an upgrade to Leiningen 2.9.0 caused a conflict with cider/piggieback 0.3.9:

```
Error loading cider.piggieback: Syntax error compiling at (cider/piggieback.clj:187:3).
...
...
...
Caused by: java.lang.RuntimeException: Unable to resolve var: cider.piggieback/wrap-cljs-repl in this context
```

Since latest Leiningen has ported to nRepl 0.6.0 which in turn is only supported by piggieback 0.4.0.

Bumping to 0.4.0 gives me Cursive REPL errors on start:

```
Error loading cider.piggieback: Syntax error compiling at (cider/piggieback.clj:1:1).
...
...
...
Caused by: java.lang.RuntimeException: Unable to resolve var: cider.piggieback/wrap-cljs-repl in this context
```

Since piggieback 0.4.0 is not compatible with tools.nrepl anymore.

We have a mixed team of Cursive, Emacs + Cider team so for now I'm remaining on 0.3.9 with Lein 2.9.0 and a broken Lein Repl and working Cursive one.
