### ISSUE TITLE
Resolve :extra-deps under aliases to be part of a project

### ISSUE THREAD

**Issue by danielcompton** [cursive-ide/cursive#2164]
I have a (partially redacted) project based on juxt/edge that looks like this:

```clojure
{:paths ["src"]
 :deps
 {org.clojure/clojure {:mvn/version "1.10.0"}
  juxt.edge/lib.app {:local/root "../lib/edge.app"}

  yada {:mvn/version "1.3.0-alpha7"}
  juxt.edge/yada.ig {:local/root "../lib/edge.ig.yada"}
  juxt.edge/bidi.ig {:local/root "../lib/edge.ig.bidi"}
  integrant {:mvn/version "0.8.0-alpha2"}

 :aliases
 {:dev
  {:extra-paths ["dev" "test"]
   :extra-deps
   {juxt.edge/lib.app.dev {:local/root "../lib/edge.app.dev"}
    juxt.edge/test-utils {:local/root "../lib/edge.test-utils"}}}

  :test
  {:extra-paths ["test"]
   :extra-deps
   {juxt.edge/test-utils {:local/root "../lib/edge.test-utils"}}}

  :prod
  {:extra-deps
   {juxt.edge/lib.app.prod {:local/root "../lib/edge.app.prod"}}}}}
```

All of the local root dependencies in the main `:deps` block are resolved correctly and show up as sub-projects, but none of the `:extra-deps` are detected or resolved. I have the `:dev` and `:test` aliases enabled. 

I think it would be most useful if all of the local roots under all aliases were resolved. I won't normally be running my deps project with the prod alias, but I may still want to look at the code for the `juxt.edge/lib.app.prod` project.

**Comment by cursive-ide** [comment]
When you say you have those aliases enabled, do you mean that you have them selected in the Aliases tree in the Clojure Deps toolwindow?

I think I'd rather leave the selection of the aliases that should be synced to the project to the user, since sometimes they can be conflicting (e.g. a `clojure-1.9` and `clojure-1.10` alias). But the local root `extra-deps` should definitely be synced from the selected aliases, yes.

**Comment by danielcompton** [comment]
Sorry, I think I've mixed things up a little bit. The main feature I'm looking for is that Cursive auto-imports all `:local/root` deps projects that are in `:extra-deps` and registers them as a deps project in Cursive. I'm not sure whether that needs to be tied to aliases or can be done separately?

**Comment by cursive-ide** [comment]
This is fixed for the next build. All `:local/root` deps from `:extra-deps` will be added as modules, if their aliases are enabled in the Deps toolwindow. It's limited to the enabled aliases because the code in an `:extra-deps` `:local/root` module may require libraries from e.g. Maven dependencies from the same alias, and those won't be present if the alias isn't enabled.

I'm interested in experience reports on how this works in practice, and I'm happy to revisit it if required.

**Comment by danielcompton** [comment]
Awesome! What will happen If I turn on the prod alias to force the prod local/root dependencies to be detected, then disable the alias again?

**Comment by cursive-ide** [comment]
The modules will be removed again.
