### ISSUE TITLE
Using `:override-deps` with `:local/root` from `~/.clojure/deps.edn` does not add module

### ISSUE THREAD

**Issue by awkay** [cursive-ide/cursive#2204]
When I'm working on libraries from a project I often need to set `:local/root` in order to be able to edit the source as I work. This works perfectly when I do it in the project's deps.edn directly (it adds the library as a module), but if I put the library artifact in `~/.clojure/deps.edn` and use `:override-deps` the numbered version disappears from my list of external libs in the project pane, but it does not add the library as a module.

Steps to reproduce:

1. Clone a project and one of the libraries it uses
2. Add an `:override-deps` alias to your global deps.edn that points to the library.
3. Import the project, go to deps pane in IntelliJ, check the overridden alias.

The external libs change, but the module is not added.

**Comment by onetom** [comment]
> check the overridden alias
What does this mean?
What should be checked about the alias?
Did you mean "check the dependency"?
Still, how should it look like?

> The external libs change,
"external libs" as in the tree under the _Dependencies_ branch?

> but the module is not added.
"module" as in IntelliJ module?
not added where?

**Comment by onetom** [comment]
I've noticed another strange behaviour when using `:local/root`. If the path specified for `:local/root` is an absolute path, Cursive is able to navigate to the source code of the dependency, but with a relative path it can not even start a `clojure.main` REPL, because it fails with the following error:
```
Syntax error (FileNotFoundException) compiling at (vlaaad/reveal/ui.clj:1:1).
Could not locate cljfx/api__init.class, cljfx/api.clj or cljfx/api.cljc on classpath.

Full report at:
/var/folders/2y/8p3dxqr946v837dq1bp3t3t40000gn/T/clojure-3297519447358867038.edn
```

There is no error, when ran from the command-line.

# Failing config

The project `deps.edn` contains the following aliases:
```
  :reveal {:extra-deps {vlaaad/reveal {:git/url "ssh://git@github.com/gini-app/reveal.git"
                                       :sha     "d0fe2216ded151530a7e665771164c1bfca9765d"
                                       :tag     "master"}}
           :main-opts  ["-m" "vlaaad.reveal.repl"]}

  :reveal-upstream
          {:override-deps {vlaaad/reveal {:mvn/version "0.1.0-ea24"}}}

  :reveal-local
          {:override-deps {vlaaad/reveal {:local/root    "../../reveal"
                                          :deps/manifest :deps}}}
```

No error, when ran as `clj -A:reveal:reveal-local`

# Successful config

`~/.clojure/deps.edn` contains the following alias:
```clojure
 {:reveal-dev
            {:override-deps {vlaaad/reveal {:local/root    "/Users/onetom/gini/reveal"
                                            :deps/manifest :deps}}}
```

Cursive can run a `clojure.main`  REPL and _Local vlaaad/reveal_ item also appears in the _Dependencies_ tree of the _Clojure Deps_ tool window, with a module icon as opposed to a library icon, like the other dependencies.

It's also possible to navigate in the editor pane to files within this `:local/root` dependency, using `Cmd-B`, however `Alt-F1` / _Project_ (_Select in Project View_ action) does not select the correct file, because it's not present anywhere in the _Project_ tool window.
 
Also no error, when ran as `clj -A:reveal:reveal-dev`

As discussed in https://github.com/cursive-ide/cursive/issues/1641#issuecomment-664513197, even in this case the development of the `:local/root` lib is not possible, because trying to load a file from the lib results in a `_Cannot load xxx.clj file into the active REPL. It is not in scope for the module used to start the REPL.`

**Comment by awkay** [comment]
As far as I can tell this is fixed, and has been for some time. Closing the old issue.
