### ISSUE TITLE
Sending comment form to REPL causes syntax error

### ISSUE THREAD

**Issue by Folcon** [cursive-ide/cursive#2219]
Sending the form below using `SHIFT-CMD-P` gives the error:
```
(comment "")
Syntax error compiling at (form-init9046503223409590555.clj:1:1).
Unable to resolve symbol: comment in this context
```
Is this not the correct way to send forms to the REPL? Also I don't think the send form to REPL is documented in the user-guide.

**Comment by cursive-ide** [comment]
It is documented at the end of this section here: https://cursive-ide.com/userguide/repl.html#interaction-with-the-editor, but you're right that it's very brief and doesn't mention the comment feature.

When you're sending the form, do you have the caret on the `""`? Otherwise it will send the whole comment form, which is not what you want. I'm not sure about that error, but check that it is actually the `""` being sent and not the full `(comment "")`.

**Comment by Folcon** [comment]
So this is what I tested, all using `SHIFT-CMD-P`:
```clojure
(comment "")|

=>
(comment "")
Syntax error compiling at (form-init9046503223409590555.clj:1:1).
Unable to resolve symbol: comment in this context


(comment ""|)

=>
(comment "")
Syntax error compiling at (form-init9046503223409590555.clj:1:1).
Unable to resolve symbol: comment in this context


(comment |"")

=>
(comment "")
Syntax error compiling at (form-init9046503223409590555.clj:1:1).
Unable to resolve symbol: comment in this context
```

I even tried:
```
(let []
  (comment ""))|

=>
(let []
  (comment ""))
Syntax error compiling at (form-init9046503223409590555.clj:1:1).
Unable to resolve symbol: let in this context
```

However at the REPL:
```
(comment "")
=> nil
(let []
     (comment ""))
=> nil
```

I'm not certain if this is intended behaviour however?

**Comment by Folcon** [comment]
appears to have been fixed =)...
