### ISSUE TITLE
"cannot be resolved" error for clojure symbols when using deps.edn

### ISSUE THREAD

**Issue by sirwobin** [cursive-ide/cursive#2222]
I am using IntelliJ 2019.2 with cursive plugin on up to date MacOSX.  Project SDK is Java 12 and  Clojure tooling was installed with homebrew.

I have made a very simple project with deps.edn and one file in the src directory.  From command line I can start clojure repl with `clojure` then load the one namespace and execute the one function inside that NS.  To make sure that dependency management is working fine, I have included the yada library and I can confirm that I am able to require yada.yada NS from the clojure REPL.

[deps.edn.txt](https://github.com/cursive-ide/cursive/files/3530228/deps.edn.txt)
[core.clj.txt](https://github.com/cursive-ide/cursive/files/3530230/core.clj.txt)

I opened the project in cursive, selected deps to manage dependencies, set SDK to Java 12, had to add the "src" folder as a source root in the IDE then opened the one file containing the NS code.  The symbols "ns", "defn" and "println" are highlighted hello and when I hover the mouse over them I see the error "ns cannot be resolved", "defn cannot be resolved" and so also for println.

**Comment by cursive-ide** [comment]
I think this is probably caused by #2209. Unfortunately due to [platform issues](https://groups.google.com/d/topic/cursive/ntvsiLAehY0/discussion) Deps is basically unusable with 2019.2. I'm working on a migration to fix this from the Cursive side rather than waiting for the platform issues to be fixed, but in the meantime downgrading IntelliJ to 2019.1 is the best option for Deps stability. As detailed in that thread 2019.1 has its own set of issues, if you just don't want problems, 2018.3 is the most stable version for now.

**Comment by jonathan-arrender-smith** [comment]
I seem to be getting exactly the same with a deps project under IDEA 2020. Unfortunately I use IDEA for other projects and languages so not so easy to go back to the older version. Any recommendations?

**Comment by cursive-ide** [comment]
@jonathan-arrender-smith Can you try the suggestions here and see if they help? https://cursive-ide.com/userguide/eap/troubleshooting.html#help-lots-of-symbols-don-t-resolve
