### ISSUE TITLE
Unable to import project from deps - deps.edndeps.edn

### ISSUE THREAD

**Issue by erichall** [cursive-ide/cursive#2238]
I'm unable to import an existing project as deps. The error is Couldn't read deps.edndeps.edn (No such file or directory)

I'm running IntelliJ version 2019.2.2.

![image](https://user-images.githubusercontent.com/8048667/65370482-6c60e400-dc59-11e9-9b83-08d566e4c336.png)

**Comment by cursive-ide** [comment]
Which version of Cursive are you using?

**Comment by cursive-ide** [comment]
I actually ran into this the other day and finally figured it out. There's a bug in Cursive 1.8.2 where for confusing reasons it will pick up a deps.edn in your user home directory. This is fixed in the 1.9.0 series (currently in EAP, will be stable shortly). As a workaround, just delete or move the deps.edn in your home folder.

I'll close this since it's fixed in more recent versions.
