### ISSUE TITLE
Alias :main-opts not respected for nREPL configuration

### ISSUE THREAD

**Issue by samwagg** [cursive-ide/cursive#2322]
I have a deps.edn with the following alias defined:
```
:repl {:main-opts ["-i" "aot.clj" "-r"]}
```
When I run `clj -A:repl` on the command line, `aot.clj` gets run:

When I run in Cursive using the REPL config below, `aot.clj` doesn't get run:
<img width="867" alt="Screen Shot 2020-02-24 at 9 08 25 AM" src="https://user-images.githubusercontent.com/8338672/75192714-a141fd00-5709-11ea-8995-548f78ae9138.png">

If I instead use `clojure.main` for the REPL type, `aot.clj` does get run as expected. 

### Version info
OS: MacOS Mojave
Intellij: 2019.3.3 (Ultimate Edition)
Cursive: 1.9.0-2019.3

**Comment by cursive-ide** [comment]
This is fixed, sort of, for the next build. The way this works when running an nREPL server is that Cursive creates a temporary clj file containing the code to start the server, and then invokes it with `-i <temp-file>.clj`. The init file in turn invokes `nrepl.cmdline/-main`, which includes this code:
```clojure
;; need to hold process open with a non-daemon thread
;;   -- this should end up being super-temporary
(Thread/sleep Long/MAX_VALUE)
```
Cursive was actually adding the options from `:main-opts` after the `-i`, but they were never being executed because the main thread was permanently asleep. Cursive now adds them prior to the `-i` option, but that has a drawback. According to [the docs](https://clojure.org/reference/repl_and_main#_clojure_main_help) `-i` is an init option, and they must appear before any main options. So the upshot is that when running a REPL via Cursive, only init options (`-i`, `-e` and `--report`) shoud be in `:main-opts`. Hopefully that's not too onerous.

**Comment by imrekoszo** [comment]
@cursive-ide would it be possible to put this behind a flag per repl config? Sometimes I want to repl into an alias that has main opts set up (like for running tests) without executing main-opts.

**Comment by cursive-ide** [comment]
@imrekoszo Yes, I'm planning to re-work how this works as part of #2409, I'll try to make that case work too.
