### ISSUE TITLE
Cursive is unable to understand project when deps.edn is a symlink

### ISSUE THREAD

**Issue by imrekoszo** [cursive-ide/cursive#2360]
Demo repository: https://github.com/imrekoszo/depslink - should be unable to properly load in Cursive.

Repro steps starting from a working project:

1. Create empty deps project
2. Create the `resources` folder and add it as `:paths` to deps.edn
3. Note that the project works at this point
4. `mv deps.edn resources/project-deps.edn`
5. `ln -s resources/project-deps.edn deps.edn`
6. Refresh the project in Cursive
7. Cursive will report an error and the project becomes unusable (reported using Intellij's built in tool under `#2363`)

Environment:

`Cursive 1.9.2-eap1-2020.1`

```
IntelliJ IDEA 2020.1.1 Preview (Community Edition)
Build #IC-201.7223.18, built on April 17, 2020
Runtime version: 11.0.6+8-b765.38 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Non-Bundled Plugins: Key Promoter X, String Manipulation, com.github.gtache.lsp, mobi.hsz.idea.gitignore, JMeter plugin, StringToolsPlugin, com.cursiveclojure.cursive, org.jetbrains.kotlin, com.tang, gherkin, name.kropp.intellij.makefile, net.seesharpsoft.intellij.plugins.csv, Docker, ru.adelf.idea.dotenv
```

**Comment by imrekoszo** [comment]
Thanks for taking a look at this. I re-checked this with the latest EAP. This time I disabled all plugins but Cursive, the built in terminal and the mac os light theme.

I no longer get the exception when I do the transition to symlinked deps.edn (so that could have been some other plugin) but the project still becomes unusable and the project tool window won't show anything but deps.edn and the iml file for the project.

**Comment by cursive-ide** [comment]
Ok, this turned out to be extraordinarily complicated. I _think_ I have it fixed, but because it deals with IntelliJ's virtual file system and the listener system it's possible there's still some funkiness there - let me know if you see any.

One thing, using your repro steps, when you move the deps file and create the symlink, at that point the project will be removed from IntelliJ (it detects the deletion of the project file but has troubling linking it to the creation of the new symlinked file). In that case you'll have to reimport the file but it should work after that.

**Comment by imrekoszo** [comment]
Wow, nice one, thank you for tracking it down. I'll try it as soon as I can and let you know.

Based on what you wrote I suspect if you close the project while doing the file move and symlink and reopen it afterwards then you should be grand. I'll also try that.

**Comment by imrekoszo** [comment]
Both of these seem to work with 1.9.2-eap3, thank you very much for the quick action!
