### ISSUE TITLE
Java functions not resolving after calling `first` on `List<...>`

### ISSUE THREAD

**Issue by The-Alchemist** [cursive-ide/cursive#2390]
## Description

It seems Cursive cannot recognize Java interop calls after calling `first` on a `java.util.List`.  Probably other sequence functions and Java collections too.

## Java code

```java
import java.util.List;

public class PersonList {
    public static List<Person> getList() {
        Person p = new Person();
        return List.of(p);
    }
}

public class Person {

    public String getName() {
        return "Alice";
    }
}
```

## Clojure code
```clojure

(deftest something
  (let [l (new PersonList)]

    (is (= "Alice" (-> l first .getName)))
    ))
```

## Cursive screenshot

![image](https://user-images.githubusercontent.com/812287/84597257-dd23de00-ae30-11ea-95b4-44bebe5c42cb.png)

So, Cursive knows that it's a Java `List` because I can hover over `l` and it recognizes that it's a `java.util.List`.  But it doesn't recognize `.getName()`.

Maybe it's a bridge too far to recognize stuff like stuff because of erasure.  Not sure if Cursive analyzes the bytecode or does some kind of static analysis on the raw `.java` files.

**Comment by cursive-ide** [comment]
Yes, this will unfortunately never work, because `first` has no type information, and there's no way for Cursive to know what `first` does to a list without hard-coding that information. Clojure itself can't know this either, and while your code works it will be very slow because the `.getName` call will be reflective. 

Clojure in general doesn't understand generics, so even `(-> l (.get 0) .getName)` won't work - that one is because of type erasure, though. Cursive could have a better understanding of those types and warn the user when the results won't be what they expect, but it currently doesn't go that far.

**Comment by The-Alchemist** [comment]
Thanks, @cursive-ide !

It looks like the solution (for me, who wants to avoid Cursive warnings/errors), is to type-hint the return value of `first`:

```clojure

(deftest something
  (let [l (new PersonList)]

    (is (= "Alice" (-> l (^Person first) .getName)))
    ))
```

... which makes the call non-reflective _and_ avoids the Cursive warning.

Perhaps, long-term,  Cursive can recommend type hints, like IntelliJ does for Java (e.g., "Unused import statement" `->` "Optimize imports")?

**Comment by cursive-ide** [comment]
Yes, I plan at some point to have Cursive suggest type hints for cases like this, and also possibly suggest to move them around to minimise them (for example, type hinting declarations rather than uses).

**Comment by The-Alchemist** [comment]
Thanks, @cursive-ide , and please keep up the great work!  💯
