### ISSUE TITLE
[Deps] resources dir incorrectly classified in IntelliJ's project structure

### ISSUE THREAD

**Issue by boschi** [cursive-ide/cursive#2400]
When importing a DEPS project, the directories "resource" and "test-resources", listed in the `:extra-paths` key in `deps.edn` file are being marked as "Source" and "Test" respectively in the IntelliJ project Structure.

Is it possible to have them marked as "Resources" and "Test Resources", as I believe they should?

**Comment by cursive-ide** [comment]
This is fixed for the next release. The problem is that deps does not distinguish between resource and source directories, it only cares about directories on the classpath. However, directories from `:extra-paths` (or indeed just `:paths`) will be marked as source roots, and then you can right click them in the project view and select _Mark Directory as... | Resources root_. This will then remember that you selected that, and on future project syncs will create the directory as the same type.

This was previously done for test folders too, since deps similarly doesn't really have a concept of what is a source or test folder. However, that selection was not stored in configuration where it would be shared with co-workers via VCS. Both types of configuration (test, resource, etc) now use the same mechanism and will be shared.

**Comment by cursive-ide** [comment]
Fix released in 1.13.4-eap1 on 2024-05-19.

**Comment by cursive-ide** [comment]
Fix released in 1.13.4 on 2024-08-06.
