### ISSUE TITLE
Multiline TODO matchers would be nice

### ISSUE THREAD

**Issue by devurandom** [cursive-ide/cursive#2524]
IntelliJ supports multi-line TODO and FIXME comments: https://www.jetbrains.com/help/idea/using-todo.html

This seems to be missing in Cursive / for Clojure files and comments.

This feature was originally implemented for IntelliJ here: https://youtrack.jetbrains.com/issue/IDEA-62161
There are several relates-to linked issues for the different JetBrains IDEs, so I assume this has to be implemented per-IDE or per-language. Hence my suspicion that Cursive might not yet have implemented this. If it is already implemented, I was unable to find the setting to enable it.

**Comment by onetom** [comment]
I'm more and more certain, that I have OCD, because as I'm using this feature more often, I get annoyed by the different coloring of the subsequent lines.

My consolation is that https://github.com/tarsius/hl-todo does even less coloring, so that's 1 less reason for being tempted to "switch to Emacs" ;D

**Comment by cursive-ide** [comment]
This is fixed for the next build. I actually thought I had fixed this already, but there was a bug in the implementation.
