### ISSUE TITLE
Support adding brick as :extra-deps for a Polylith workspace in development

### ISSUE THREAD

**Issue by tengstrand** [cursive-ide/cursive#2554]
The [Polylith](https://polylith.gitbook.io) architecture comes with the [poly](https://github.com/polyfy/polylith/tree/issue-66) tool written for Clojure that is based on tools.deps.

I've been working on [issue-66](https://github.com/polyfy/polylith/issues/66) for a while in the `issue-66` branch to support defining bricks as `:extra-deps` instead of `:extra-paths`, see [deps.edn](https://github.com/polyfy/polylith/blob/issue-66/deps.edn).

This works fine in e.g. Emacs/Cider and VSCode/Calva but not in IDEA/Cursive.
What happens is that the `src` directories are not recognised by Cursive and will therefore not show up as green.

Instead of this:
<img width="193" alt="brick-defined-using-extra-paths" src="https://user-images.githubusercontent.com/631272/118976844-c9082b00-b975-11eb-911f-036281b6d11c.png">

...we get this:
<img width="193" alt="brick-defined-using-extra-deps" src="https://user-images.githubusercontent.com/631272/118976784-af66e380-b975-11eb-9071-b5ea94c5de42.png">

The good part is that the code is recognised by the REPL, but unfortunately not by the IDE.
 
The workaround is to add them as `:extra-paths`, but it would be much better if they could be added as `:extra-deps` instead:
- It would be consistent with how bricks are added to other projects (development is a special kind of project).
- Instead of defining two paths, `src` and `resources`, we can define one dependency per brick, resulting in less code.
- If a `resources` directory is added or removed from a brick, the change will automatically be detected by tools.deps.

Some teams will probably start to use the `:extra-deps` way of defining bricks in development, which unfortunately will stop people that joins the team from using Cursive. With better support in Cursive, this could be avoided.

Regards,
Joakim Tengstrand

**Comment by imrekoszo** [comment]
I did try to work around this by re-importing the entire workspace into idea and marking all local/root refs as modules. That _did_ solve the folder mark problem and did not break the repl classpath: https://github.com/polyfy/polylith/issues/127

However, as @tengstrand & co kindly checked for me, it does not solve the problem of symbol resolution in case a `brick` references another `brick`'s `interface`. Due to how polylith is set up, these inter-`brick` dependencies are not listed as relative local/root deps in the `brick`s' own deps.edn files - this is how polylith achieves swappability of implementations. Multiple `brick`s might have the same `interface` signature (via some code duplication) and it's decided at the `project` (or `development`) level which `brick` to reference as a dependency to satisfy a requirement for an `interface`.

I created a repro case at https://github.com/imrekoszo/cursive-polylith

With the root deps.edn looking like
```clojure
                  :extra-deps {org.clojure/clojure {:mvn/version "1.10.3"}
                               org.clojure/tools.deps.alpha {:mvn/version "0.12.1003"}
                               poly/user {:local/root "components/user"}
                               poly/foo {:local/root "components/foo"}}}

            :test {:extra-paths ["components/user/test"
                                 "components/foo/test"]}
```

And no cross-`brick` references, `se.example.foo.interface` cannot be navigated to from the following file:

```clojure
(ns se.example.user.core
  (:require [se.example.foo.interface :as foo]))
```

**Comment by imrekoszo** [comment]
Hey @cursive-ide, thanks for picking this up. I chatted to @tengstrand on the clojurians slack about this, here's what I gathered:

As for the first problem you mention, while a convenience feature would be nice, as long as reimporting manually works, that shouldn't be a deal-breaker.

For the second problem, it appears those test paths can actually be dropped from the top-level deps.edn - it was only added there as an attempt to make it more Cursive-friendly. I went ahead and dropped those paths from the repro case in my repo.

The problem that remains after these is that `go to definition` does not work between bricks:

![Screenshot 2021-11-02 at 18 33 14](https://user-images.githubusercontent.com/1116295/139918181-389f7df9-3eae-46eb-bce5-f90ab7f58f52.png)

I'm assuming the reason why this (orange arrow) doesn't currently work in Cursive is because in polylith there must be  no reference to the `foo` brick from the `user` brick (red arrow).

> polylith quick info: `components` and `bases` are in the category of `bricks` and there must be no direct deps.edn references between `bricks`. `projects` on the other hand act as the composing layer and will reference (usually multiple) `bricks`.

In the `dev` alias (which is a special, development-type 'project') that I have selected, there are still references to both of those bricks, meaning they will both be on the classpath if I run a repl with the Idea classpath so I guess the missing connection can be figured out somehow. This should ideally work transitively, so if I have an alias selected which `:local/root` references a `project`, and that project `:local/root` references some bricks, `go to definition` should work between those bricks too.

**Comment by furkan3ayraktar** [comment]
Hi! Thank you for picking up this issue! I’m one of the [Polylith](https://polylith.gitbook.io/) team members and I’ll try to shed light on what is working and what is not working in Cursive for Polylith projects. For that, I’ll start by giving a short overview of what Polylith does. 

Polylith has these two important concepts, component and base (they are referred bricks collectively). They are the building blocks with different purposes, bases being responsible of exposing an external API and component being small Lego-like bricks implementing the logic and exposing and internal functional API. Each base and component has their own `deps.edn` file, defining their source, resource, and test folders (with `:test` alias) as well as their external library dependencies. One of the most important thing in Polylith is, bricks **do not** define internal dependencies in their `deps.edn`, they are picked up when you put them together in a project and this enables Polylith users to interchange components with different implementations. 

Polylith has a special project, which is called development project, that has a `deps.edn` file at the root of the project. Here we define our local development project and include all the components and bases in it so that we can reach to all code in the repository, even though they might be split into different projects in deployed versions.

### What is working with Cursive:
If we have the following `deps.edn` structure, Cursive works:
```clojure
{:aliases {:dev  {:extra-paths ["components/comp-a/src"
                                "components/comp-a/resources"
                                "components/comp-b/src"
                                "components/comp-b/resources"
                                "components/base-a/src"
                                "components/base-b/resources"]

                  :extra-deps  {some.external/dependency-of-comp-a {:mvn/version "1.0.0"}
                                some.external/dependency-of-comp-b {:mvn/version "1.0.0"}
                                some.external/dependency-of-base-a {:mvn/version "1.0.0"}
                                some.external/dependency-of-base-b {:mvn/version "1.0.0"}}}

           :test {:extra-paths ["components/comp-a/test"
                                "components/comp-b/test"
                                "components/base-a/test"
                                "components/base-b/test"]

                  :extra-deps  {some.external/test-dependency-of-comp-a {:mvn/version "1.0.0"}
                                some.external/test-dependency-of-comp-b {:mvn/version "1.0.0"}
                                some.external/test-dependency-of-base-a {:mvn/version "1.0.0"}
                                some.external/test-dependency-of-base-b {:mvn/version "1.0.0"}}}}}
```

This is a very simple example and you can see a realworld example [here](https://github.com/furkan3ayraktar/clojure-polylith-realworld-example-app/blob/master/deps.edn).

### What does not work in Cursive and works in other IDEs
If we have the following `deps.edn` structure, Cursive does not work by default. Even if we import each component and base as a module, it still cannot resolve namespaces from classpath for the code navigation and other features of Cursive to work:
```clojure
{:aliases {:dev  {:extra-deps  {poly/comp-a {:local/root "components/comp-a"}
                                poly/comp-b {:local/root "components/comp-b"}
                                poly/base-a {:local/root "bases/base-a"}
                                poly/base-b {:local/root "bases/base-b"}}}

           :test {:extra-paths ["components/comp-a/test"
                                "components/comp-b/test"
                                "components/base-a/test"
                                "components/base-b/test"]

                  :extra-deps  {some.external/test-dependency-of-comp-a {:mvn/version "1.0.0"}
                                some.external/test-dependency-of-comp-b {:mvn/version "1.0.0"}
                                some.external/test-dependency-of-base-a {:mvn/version "1.0.0"}
                                some.external/test-dependency-of-base-b {:mvn/version "1.0.0"}}}}}
```

Since `:local/root` syntax does not allow depending on an alias in the target `deps.edn`, we still need to duplicate test paths and extra dependencies for the tests from individual components and bases. 

### What would be ideal 😎
It would be the best If Cursive can understand that everything starting with `poly/` in the extra-deps is a Polylith component or base, and resolve their src, resource, and test directories and src and test dependencies. Then, we wouldn't need to duplicate anything and have both sources and tests in our REPL. In a Polylith workspace, components and bases always have their tests under `:test` alias, since thats where the `poly` CLI looks for.

```clojure
{:aliases {:dev  {:extra-deps  {poly/comp-a {:local/root "components/comp-a"}
                                poly/comp-b {:local/root "components/comp-b"}
                                poly/base-a {:local/root "bases/base-a"}
                                poly/base-b {:local/root "bases/base-b"}}}}}
```

Let me know if you need any further information from us. You can reach out to me or the rest of the team at [#polylith](https://clojurians.slack.com/archives/C013B7MQHJQ) channel in Clojurians Slack.

**Comment by cursive-ide** [comment]
Thanks for the examples @imrekoszo and @furkan3ayraktar. I've looked into this further, and I think I have a better idea of how Polylith works now. I'm still not sure how best to support it, though. Thinking through what I would have to do to support this, it's something like:

1. User clicks on something, or Cursive tries to resolve it in the editor.
2. Cursive checks to see it looks like the reference is contained within a brick.
3. If it is, then Cursive should construct a resolve scope for the project, probably using a union of the development project scope (for source references across bricks) and the original brick's scope (to get the dependencies of the brick itself). Or maybe just the development project's scope for everything? I'm not sure about this.

There are a couple of assumptions here. One is that there's either: 1) a 1-1 correspondence between an IntelliJ project and a Polylith project, or: 2) that bricks are in a consistent place relative to the development project so that I can find the development project from them. I'm guessing that 1) is probably not a good assumption to make, since these projects might be contained within a larger monorepo. I guess the question is: how can Cursive determine that a deps project is a Polylith development project, and modify its resolution accordingly?

I spent some time looking at the Realworld project example, and there are still cases there where the same source root is present in multiple modules, e.g. the test roots are present in both the root development project and in the components themselves. I'm fairly sure this used to be a hard error in IntelliJ but it's not complaining now, perhaps that has changed in recent versions. I'll check that with JetBrains. If my memory is correct then there's nothing I can do about that, unfortunately.

**Comment by furkan3ayraktar** [comment]
Hi @cursive-ide! Thanks for looking into this, I’ll try to elaborate on the topics that you mentioned. 

I can start with the project structure. Polylith has a strict directory structure. This is important for our own [poly CLI](https://polylith.gitbook.io/poly) to work properly. The structure is as following:

```
example              # workspace dir
├── .git             # git repository dir
├── bases            # bases dir
│   ├── base-1       # base dir
│   │   ├─ src       # base sources
│   │   ├─ resources # base resources
│   │   ├─ test      # base tests (use-case: unit tests)
│   │   └─ deps.edn  # Specifies src, resources, and test paths. Specifies only external dependencies. Always has a :test alias 
│   └── base-2
│   │   ├─ src
│   │   ├─ resources
│   │   ├─ test
│   │   └─ deps.edn
│   ...
│   
├── components       # components dir
│   ├── comp-1       # component dir
│   │   ├─ src       # component sources
│   │   ├─ resources # component resources
│   │   ├─ test      # component tests (use-case: unit tests)
│   │   └─ deps.edn  # Specifies src, resources, and test paths. Specifies only external dependencies. Always has a :test alias 
│   └── comp-2
│   │   ├─ src
│   │   ├─ resources
│   │   ├─ test
│   │   └─ deps.edn
│   ...
│   
├── development
│   └── src          # development specific code (only used during development, within REPL)
├── projects         # projects dir
│   ├── proj-1       # project dir
│   │   ├─ resources # project specific resources dir (optional)
│   │   ├─ test      # project specific test dir (optional) (use-case: integration tests)
│   │   └─ deps.edn  # Specifies resource paths, internal brick dependencies (:local/root) and any extra external dependencies (optional). Optionally has a :test alias to include bricks used only during tests but not included in the deployable artifact. 
│   └── proj-2
│   │  ├─ resources
│   │  ├─ test
│   │  └─ deps.edn
│   ...
│
├── deps.edn         # development config file
└── workspace.edn    # workspace config file (an indication that you are at the root of a Polylith workspace)
```

The `deps.edn` at the root directory is the development and it is a valid project configuration for a developer to start a REPL with the correct classpath. All brick and external dependencies (if needed) under `:dev` alias and all test paths and external dependencies under `:test` alias. There could also be [extra profiles](https://polylith.gitbook.io/poly/workflow/profile) defined by other aliases, this means not all components needs to be in the classpath (and REPL), but ideally all should be navigable from the IDE. 

The reason we need to include test sources again in the root `deps.edn` is that tools.deps does not allow to refer to an alias (`:test` in this case) via `:local/root`. If we don’t do this, test paths and dependencies won’t be in the REPL. However, we need test sources and dependencies in the bricks `deps.edn` for the poly CLI to work with [incremental tests](https://polylith.gitbook.io/poly/workflow/testing).

I do not have any experience with Intellij IDE internals, so this might be a bad idea, however I’m going to say it anyway 😂. What I think is, the bricks should not be modules, since they are not independent projects. Cursive could treat them as places where source and test paths live, and resolve them and their dependencies from the development projects `deps.edn`. 

I think assumption 1 is good enough, since that’s how Polylith works in other IDEs and I don’t see the benefit of having two Polylith workspaces in a single monorepo, it’s better to combine them to get the best out of it. When it comes to assumption 2, bricks are always in a consistent place relative to the development projects `deps.edn`. It is a flat structure under `components` and `bases` directories from the root directory of the project.

**Comment by imrekoszo** [comment]
@furkan3ayraktar I wouldn't completely rule out Colin's concerns wrt assumption 1 - workflows differ.

However, Cursive might be able to use `workspace.edn` to find polylith roots? Is that always present in the polylith root? Is there a schema/spec available for its contents, should Cursive want to also check that to differentiate from some other kind of `workspace.edn`?

**Comment by cursive-ide** [comment]
Yes, for reference the largest lein project I'm aware of had > 90 `project.clj` files. Someone somewhere is going to want to put two Polylith apps in one IntelliJ project.

**Comment by imrekoszo** [comment]
@cursive-ide is there any update on this? Could it be a possible solution to treat active `:local/root` deps, which resolve to paths within the intellij project source paths as opposed to library paths?

This is the current situation when one only uses deps - those library paths _could_ be source paths instead:
<img width="1081" alt="cursive-only-deps" src="https://user-images.githubusercontent.com/1116295/170976713-2e78d02e-3336-4e33-bdf2-d35a658f475d.png">


The following is the half-arsed workaround I use now on my poly workspaces. I reference poly bricks as both deps (to pull in their transitive deps) and paths (to satisfy Cursive). It does result in those paths still being marked somewhere half way between source and lib and so some inspections, like "namespace is not in the correct location" not work.
<img width="1087" alt="cursive-deps-and-paths" src="https://user-images.githubusercontent.com/1116295/170977213-0b9b9db2-b8f0-4482-b8f7-009aa959cdcb.png">


And the following is how it looks with the poly-recommended workaround. This has the downside of potentially having to specify multiple (src, resources etc) paths per brick _and_ not automatically pulling in deps of those bricks.
<img width="1083" alt="cursive-all-paths" src="https://user-images.githubusercontent.com/1116295/170977432-c863a40a-80fc-433b-a240-e5067da1b968.png">


@furkan3ayraktar reading back on your comments I would actually discourage using `poly/brick-name` for internal naming (and adding special cases to Cursive based on that). This can cause clashes when git-dep-referencing a poly _project_ from another poly workspace.

@cursive-ide I've updated my repro repo with the above examples.

**Comment by cursive-ide** [comment]
@imrekoszo No update sorry, I've been busy with other things. I'll try to take another look at this and think about the source path idea. At first glance I'm reluctant, because it makes the inter-module dependencies even weirder than they already are with Deps, but I haven't really thought about it in detail.

**Comment by imrekoszo** [comment]
> make it easy for Cursive to resolve Polylith bricks correctly

@furkan3ayraktar I would prefer a solution that is not Polylith-specific and I believe Colin is on the same opinion. I think there are improvements that could be made in general to how Cursive handles local/root deps and I think if that is sorted out, this issue will also be resolved.

I'm just working on a more general repro case for my suggestion above.

**Comment by furkan3ayraktar** [comment]
I agree with @imrekoszo. `:local/root` dependencies end up in the classpath as source files, and it makes sense to me to treat them as source files. I don't think it matters if it's in the Intellij project or not. However, I do not know if this makes things too complicated, so it's up to @cursive-ide to choose if the sources outside of the project should be included or not.

_One think that could be valuable for Polylith users:_ neither the Clojure CLI nor other IDEs include the test files when other projects are included as a `:local/root` dependency (since tests are defined in an alias and you cannot depend on an alias with `:local/root`). It would be nice to have a special Polylith support, so that, Cursive can detect and include the `test` files as well in the development project's Classpath automatically for Polylith projects when we start a REPL session (the ideal scenario I mentioned on [my comment above](https://github.com/cursive-ide/cursive/issues/2554#issuecomment-958734748)).

**Comment by imrekoszo** [comment]
@furkan3ayraktar thanks for reviewing this.

I would caution against the extra test-paths support however. That is something tools.deps itself doesn't do, and the current issue stems from the fact that Cursive does something differently from tools.deps. My opinion is that editors should try to match what tools.deps does so just by configuring your deps.edns you'll get the same behavior everywhere. Extras should be - and to a good extent already are - provided by the poly tool which I think is the perfect location for polylith-specific additions.

**Comment by imrekoszo** [comment]
@cursive-ide I created yet another repro case. It still isn't polylith but somewhat closer to it. Subprojects don't reference each other on a `deps.edn` level, only in code. All subprojects are added as local/root deps in the top-level deps.edn.

https://github.com/imrekoszo/cursive-local-root-2

![image](https://user-images.githubusercontent.com/1116295/183408726-f5e58ba8-6935-46f6-91f9-dc9b12e82c8c.png)

**Comment by cursive-ide** [comment]
Ok, I've spent some more time looking at this. Many thanks again to @imrekoszo for the great repro cases, they've been very helpful in terms of clarifying my understanding of the problems.

There are 3 main problems, I think:

1. Cursive complains about files not being under a source root when a file is in a `:local/root` dependency which is _not_ added as a module in IntelliJ.
2. IntelliJ puts files in reader mode when they're in library roots, even if they're also in source roots. I think this must be a recent platform change. This is what causes the lack of incorrect namespace warnings in `:local/root` deps which _are_ added as modules to IntelliJ.
3. Find Usages has various failure cases due to the way in which Polylith treats dependencies.

Cases 1 and 2 are quite easy to fix, and are basically just generic bugs in the way Cursive supports Deps. The one case which might be tricky to solve is git deps, which will also use source roots on the local hard drive, but they're not `:local/root` deps that you're likely to want to edit.

Case 3 is tricky. The bricks have dependencies which are not explicitly expressed in the code anywhere, and it's up to the developer to ensure that the code has all its dependencies fulfilled at run time. Bricks are not valid code on their own, which is an unusual code structure. What this means is that if you're searching for usages of a particular program element, it could literally be anywhere in your project. 

Rather than trying to add a bunch of Polylith-specific code to handle this case, I think the best option would be to have a per-project config flag, which basically says to treat the whole project as one big classpath. So, for navigation, find usages etc, basically just tell Cursive that elements could be located anywhere and Cursive must search the whole project for them. This might cause some strange effects, but I can't think of any off the top of my head. This might even be useful for other types of projects doing funky things with the classpath, I'm not sure.

One thing I could do is try to detect at project open if a project is a Polylith project (based on the presence of a `workspace.edn` or something) and prompt the user via a notification to turn that flag on for that project.

**Comment by tengstrand** [comment]
Hi Colin! I suggest that the `development` project + the `default` profile (if used) should be used as default within the workspace, and that Cursive only see the bricks specified in that project and profile + their libraries + libraries specified in the `development` project itself (I use the Polylith definition of a project here). This is the way most people will use Polylith, working in a single REPL from the `development` project. Being able to switch to another profile would be useful also (as a way to "simulate" different production environments). Being able to switch to other projects than `development` is less important, but could be good to have. Remember that profiles are only used by the `development` project, not the projects under the `projects` directory.

**Comment by marksto** [comment]
@cursive-ide Hi Colin! Are there any plans to incorporate the `:extra-deps` (i.e. `:local/root` deps) fix into Cursive soon? It's quite annoying that now one have to use `:extra-paths` instead + duplicate all the components' library deps within the `:dev` alias as a workaround specifically for Cursive. It ruins an otherwise perfectly good Polylith-stuffed dish. =)

Having a per-project config flag, which tells IDE to treat the whole project as one big classpath, also sounds good. While adding a Polylith project autodetection and prompting the user to turn that flag on, imho, is a cherry on top. Overall, it would be great to have Navigate to Declaration and Find Usages working for Polylith projects.

P.S. I think it's good to note, that in [the comment above](https://github.com/cursive-ide/cursive/issues/2554#issuecomment-1342195397) Joakim is talking about the `deps.edn` located in the root directory (a.k.a. the `development` Polylith project). It is this `deps.edn` that requires Cursive-specific manipulations that I've mentioned above.

**Comment by cursive-ide** [comment]
@marksto I have a plan to fix this, but it's a very large change which will affect all deps users, so I'm trying to figure out the best time to make it. It will probably be the next major release of Cursive, it's not something I want to ship in a point release.

**Comment by tengstrand** [comment]
Hi! 
Just want to draw your attention to [this](https://github.com/polyfy/polylith/discussions/301) discussion about how to best support ClojureScript in the poly tool @cursive-ide.

**Comment by cursive-ide** [comment]
Ok, a fix for this has finally been released in 1.13.0-eap2. It's a massive change in the deps support, which the Polylith support mostly just falls out of. All the issues reported by @imrekoszo in his test repos and other Github issues are now fixed. When using Polylith, users will need to check the _Preferences | Languages & Frameworks | Clojure | Project Specific Options | Resolve over whole project_ option, which will fix the project resolution issue. In the end I went for simply resolving over the whole project, which has the advantages of a) simplicity, both in implementation and ease of understanding for end users, and b) not being Polylith-specific. The Polylith RealWorld example repo syncs correctly now, and as far as I can tell behaves sanely.

As I say, this is a huge change so things may have broken. I'm also interested to know if there are things that I've missed or that don't work correctly - I don't use Polylith myself so this is hard for me to evaluate.

Many thanks again to @imrekoszo for the repro repos, they were invaluable in ensuring that everything works as expected.

**Comment by imrekoszo** [comment]
Great news Colin, thank you so much! Can't wait to try it :)

**Comment by tengstrand** [comment]
Hi Colin!

Thanks for fixing this @cursive-ide! This is really great news!

I downloaded and installed:
IntelliJ IDEA 2023.2 EAP (Ultimate Edition), Build #IU-232.8453.116, built on June 29, 2023
...and Cursive 1.13.0-eap3-2023.2.

I started my REPL with these settings:
![image](https://github.com/cursive-ide/cursive/assets/631272/85875f6c-20ef-43fa-a8a5-9d8e0915b5c6)

And with this:
![image](https://github.com/cursive-ide/cursive/assets/631272/bd41a412-3536-4a1e-9451-8a284c042a51)

The IDE recognises the components:
![image](https://github.com/cursive-ide/cursive/assets/631272/9ec22465-c31d-4c39-8953-a6f0ebaaed04)

But I can't follow links to other components (row 18 and 20):
![image](https://github.com/cursive-ide/cursive/assets/631272/098c5931-3194-4d13-af36-61405e8de4e5)

I have pushed the code to the [issue-205](https://github.com/polyfy/polylith/tree/issue-205) branch if you want to try it out.

Except from that, everything seems to work!

**Comment by tengstrand** [comment]
Sorry, forgot to check "Resolve over whole project"!

![image](https://github.com/cursive-ide/cursive/assets/631272/4469ee77-9917-4396-816e-1714c906a3ad)

With that checked, it works!

Thank you so much Colin and @imrekoszo for all the great work on this!

/Joakim

**Comment by cursive-ide** [comment]
@tengstrand Glad it worked well! There are still some kinks in the implementation, but they should hopefully get stabilised over the next week or so.

**Comment by tengstrand** [comment]
Hi again!

I have tested some more and when using [profiles](https://polylith.gitbook.io/poly/workflow/profile) the navigation could be improved so that the tool can navigate to the correct component (the one that is included by the selected aliases).

If I understand correctly, this is something that works in e.g. Calva today, and it would be nice if it could work in Cursive too!

So if we for example include the [system interface](https://github.com/polyfy/polylith/blob/393145cc39aaa4c2e9f8bfc04957988b860d076f/components/help/src/polylith/clj/core/help/deps.clj#L3):
<img width="517" alt="image" src="https://github.com/cursive-ide/cursive/assets/631272/2a4926a7-54c4-44df-b290-4308428e3829">

And try to navigate to the `system` component via its interface, Cursive can't figure out which implementation of that interface it should use (the `system` or `system-x` component in this case):
<img width="783" alt="image" src="https://github.com/cursive-ide/cursive/assets/631272/ef842e5c-9526-49a5-8eef-71f91742cca2">

These two components live under the `components` directory and use the same namespace (the same interface in Polylith terms):
<img width="274" alt="image" src="https://github.com/cursive-ide/cursive/assets/631272/740e7590-b777-4730-bb67-1be595e5be2e">

The `poly` tool forces us to select *either* the `:+default` alias (the `default` profile in Polylith terms) or the `:+plain` alias when executing commands, and doesn't allow us to use both at the same time (it detects that `polylith.clj.core.system` is included twice). Here the `plain` profile is selected:
<img width="245" alt="image" src="https://github.com/cursive-ide/cursive/assets/631272/fdaf50f1-9656-4ce6-9384-ed664ac457ff">

 In the example above, we have the `plain` profile selected (the `:+plain` alias) which holds the source code for the `polylith.clj.core.system.interface` namespace in the `system` component:
https://github.com/polyfy/polylith/blob/393145cc39aaa4c2e9f8bfc04957988b860d076f/deps.edn#L95-L96

Now when we know that `polylith.clj.core.system.interface` is only included once, the tool should be able to navigate to the correct component.

It may be good to know that the naming convention for profile aliases is to begin with a +.

**Comment by tengstrand** [comment]
I found one more problem.

When I run the `polylith.clj.core.creator.workspace-test` test from within the IDE, it doesn't recognise `polylith.clj.core.test-helper.interface` when I include `test-helper` using `:extra-deps`, but it works when I included it using `:extra-paths`, see [this](https://github.com/polyfy/polylith/commit/e4037141520b372e54b02d71a5fc52076f69d4b1#diff-551f87f7577a57c2f4f74b35056d5c7985331f7a38976810fd2bbc213bfe7bb5) commit.

**Comment by cursive-ide** [comment]
I had a look at the multiple references problem. I think there's a bit of a tradeoff here, this probably will work in Calva because Calva uses REPL introspection for its navigation, and presumably you only have one copy loaded into the REPL at any one time. However, that also comes at the cost of not being able to navigate to the other one, which I can imagine you might want to do - if you're working on one and you change the interface, for example, you're going to want to change the other too, and you won't be able to using a REPL-based system unless you restart your REPL. 

That said, this should work better in Cursive, and I'm not sure why it doesn't. Here, I have `+plain` selected and you can see that only one of these has a module created, and the other doesn't even have a source root, but IntelliJ still finds the usage:

<img width="243" alt="Screenshot 2023-07-05 at 15 57 17" src="https://github.com/cursive-ide/cursive/assets/5589171/7542de21-0144-4640-ac77-422b5224d59c">

I'll see if I can figure that out. If that were not the case, then you could switch from one to the other in the deps tool window by just selecting the right alias and refreshing, which seems pretty light-touch. I'll try to look at this at some point, but I'm super busy right now and this seems like a nice-to-have at best. I'll see what I can do.

**Comment by cursive-ide** [comment]
I looked at the test problem too, and using the following run config the test works for me with `test-helper` pulled in using `:extra-deps`:
<img width="1152" alt="Screenshot 2023-07-05 at 16 07 46" src="https://github.com/cursive-ide/cursive/assets/5589171/08808631-ab0c-4b53-9de4-ffb9d54619ae">

**Comment by tengstrand** [comment]
I found the problem. I had to select `polylith` as module, and now the `polylith.clj.core.creator.workspace-test` test also works with these settings (Run with IntelliJ project classpath) :

<img width="1244" alt="image" src="https://github.com/cursive-ide/cursive/assets/631272/e4f7f236-94ab-4067-af77-1c94e7e3c0c7">

There is still one problem left. Every time I run the tests by clicking on the two green arrows at the top left corner:
<img width="943" alt="image" src="https://github.com/cursive-ide/cursive/assets/631272/092796d7-fceb-4018-b74b-43205247db8b">

...a new configuration is created, where module is set to `creator` instead of keeping it as `polylith`:
<img width="1249" alt="image" src="https://github.com/cursive-ide/cursive/assets/631272/9f835f1e-db82-469f-892f-36de5f7c8439">

It would be good if the tests were always executed using the `polylith` module (this worked in earlier versions of Cursive).

**Comment by cursive-ide** [comment]
The problem is that that code is actually in the creator module, so IntelliJ defaults it there. You can set the defaults for many things per-project under "Edit configuration templates", but I don't think you can default the module, I think that's defaulted by context. I've filed #2818 to try to address that.

**Comment by tengstrand** [comment]
Okay nice that you are looking into this in the new issue.

I've been using Cursive for years, and as I remember, it has always been possible to execute tests directly from the IDE, without changing the configuration for each test. 

Is this a new behaviour? Just curious.

**Comment by cursive-ide** [comment]
Just to be clear, the idea would be to modify the default for each test _type_ (e.g. clojure.test), and then all tests generated from that template (including running via the gutter arrows etc) will just work. And if you create tests manually and set the module, that will work right now. It's only the automatic creation of tests from context which doesn't work now.

It's not a new behaviour as such, but Polylith uses a very unusual project style. In most other systems, components would be expected to be self-contained, and the tests in a component would be expected to work without having to run them in the context of the parent project. It's just a side-effect of that.

There is one possible alternative strategy for this change, which is just to sync the whole project as one module, and not treat the `:local/root` deps as separate components at all. So then, instead of the "Resolve over whole project" option, you'd have a "Sync whole project as one" option under the deps config, or something like that. That would fix this problem, but might cause others. For example, if users mistakenly add a sub-module as a deps project there's no good way to detect that and strangeness might result. Unfortunately I'm going away with my family shortly, and I don't have time to try that alternative out in a safe manner before I go. When I get back I can try it and we can see if it works better as a solution for Polylith.

**Comment by cursive-ide** [comment]
Ok, that fix is out in eap7. If you edit the run config templates and set the module there, then that module will be used for all configs generated from context. This will work for test running, as well as local REPLs and Clojure application configs (e.g. running `-main` from the gutter). You should also be able to store these templates in the project dir.

It's an imperfect solution, but hopefully it works well enough.

**Comment by tengstrand** [comment]
Executing tests from the IDE works as expected now. Thanks!

I want to comment on something you wrote before:
"However, that also comes at the cost of not being able to navigate to the other one, which I can imagine you might want to do"

As a user of a Polylith codebase, you have to pick exact one implementation of an interface (component) per project. This is true for the development project too, when it comes to working in the REPL, running tests and navigating the code. The only difference between the development project and other projects is that the dev project includes all components, even those that are not part of the active profiles, but we still want the user experience as if we only have access to one set of components at a time (components in the project + components in active profile(s)).

If we make small changes to an interface for a component that has multiple implementations of an interface, then we have two options as I see it:
- If it's a small change, we can update that other component's interface directly, by opening it "manually" (not navigating to it) and edit it, even though the IDE will not recognise it as source code.
- If it's a bigger change, then we switch profile so that this component will be the active one, and then the IDE will also recognise it as source code, and we will get all the code and navigation support that the IDE provides.

Having to select between several implementations every time you navigate in the IDE is a bit annoying and gives a bad user experience in my opinion.

If this last bit could be fixed, then users of Cursive would have a really nice user experience when working with Polylith codebases!

I really appreciate all the work you have done so far! Now spend some time with your family!
