### ISSUE TITLE
Midje tests result in lots of warnings

### ISSUE THREAD

**Issue by savagematt** [cursive-ide/cursive#267]
Because Midje relies heavily on `immigrate` etc. (I think), Cursive can't pick up defs of checkers and checkables, resulting in a screen full of yellow highlights.

**Comment by ohurvitz** [comment]
Any news on this?

**Comment by kidpollo** [comment]
how do tou even run Midje tests on cursive?

**Comment by ohurvitz** [comment]
I think I was able to run them by wrapping them in clojure.test tests. 
But the issue here is Cursive showing the midje syntax as errors in the editor.

**Comment by cursiveclojure** [comment]
Right, there are two issues. As @ohurvitz says, you can run Midje tests by wrapping them in clojure.test tests, but the real problem is the warnings in the editor. I've been slowly working on Midje support but it's very difficult due to its extensive use of macros. Hopefully I'll have something soon.

**Comment by klauswuestefeld** [comment]
Hi, any news on this?

**Comment by mmacphail** [comment]
I'ld be very interested in support !

**Comment by cursive-ide** [comment]
As I commented in #1918, Cursive will almost certainly not be getting Midje support, so I'm going to close this.
