### ISSUE TITLE
Nested requires not resolved in 1.12.2-2022.1 / IntelliJ IDEA 2022.1

### ISSUE THREAD

**Issue by dekelpilli** [cursive-ide/cursive#2676]
I upgraded to cursive 1.12.2-2022.1 and IntelliJ IDEA 2022.1, and now nested `require`d namepsaces aren't being resolved:

```clj
(ns my-app.core
  (:require [clojure.string :as s] ;resolved correctly
            [my-app.util :as u] ;resolved correctly
            [my-app
              [database :as db] ;not resolved
              [other] ;not resolved
              [other2 :as o2]])) ;not resolved

(defn eg []
   (+
      u/one ;no warning
      o2/two)) ;o2/two cannot be resolved
```

**Comment by cursive-ide** [comment]
I think this change has happened because the grammar has been tightened up and now only accepts lists for prefix forms. The [How to NS](https://stuartsierra.com/2016/clojure-how-to-ns.html) doc as well as the [doc](https://clojuredocs.org/clojure.core/require) for require both make it clear that these should be lists to distinguish them from simple require forms.

**Comment by cursive-ide** [comment]
I've discussed this with Alex Miller since the core specs also accept vectors. I'll fix this in the next build.
