### ISSUE TITLE
File Structure support for EDN files

### ISSUE THREAD

**Issue by markaddleman** [cursive-ide/cursive#2706]
In reference to https://clojurians.slack.com/archives/C0744GXCJ/p1654265565732809

My specific use case is deps.edn .  I'd like to open the file structure browser, type in a few characters of a dependency to jump to that point in the file.  I believe IntelliJ's has file structure support for JSON files and I imagine EDN support would be very similar.

![Screenshot 2022-06-03 9 43 22 AM](https://user-images.githubusercontent.com/2218806/171877247-ad291ec1-dc13-4492-ab9a-bdbc01b98957.png)

**Comment by onetom** [comment]
Interesting idea... I've tried `jet -p -o json < deps.edn > deps.json` and here is how it would look like, with the source popup (<kbd>Opt-Space</kbd>) on its right, as a content preview for the selected subtree:
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/56646/172285931-69219860-1b2c-45d6-a452-b9953e6a3744.png">

**Comment by serioga** [comment]
Hm, why only in EDN files?

**Comment by cursive-ide** [comment]
@serioga Because there's already structure support in Clojure files. I've only added breadcrumb support for EDN files for the moment since it's easier, but I'll add it for Clojure shortly.

<img width="611" alt="Screenshot 2023-09-25 at 22 36 26" src="https://github.com/cursive-ide/cursive/assets/5589171/fae3b7ad-9e72-4ea9-acbe-5bd9827e15fe">

**Comment by serioga** [comment]
Well, it would be totally great to have structure support integrated with Navigation Bar as well, like in other languages.

![2023-09-25_121500](https://github.com/cursive-ide/cursive/assets/527113/8f9a4c3c-045b-46a6-bbfd-9524788c0970)

**Comment by serioga** [comment]
Also now I see an empty bar in clj files, in place of breadcrumbs...

**Comment by cursive-ide** [comment]
Yes, my plan is to integrate the nav bar support in the next EAP. Once that is in, I will probably disable the breadcrumb support by default, but you'll be able to switch it on in the settings. This is how Java and Kotlin currently work. 

The empty bar is unfortunate, but that's just because I haven't implemented the breadcrumbs for CLJ yet, only for EDN. I can't turn it on for one and off for the other, because IntelliJ considers them the same language. Once I have both implemented that will show the breadcrumbs (assuming you have them enabled).

**Comment by cursive-ide** [comment]
The next EAP has full support for breadcrumbs in Clojure (no empty bar), and also has nav bar support for Clojure code.

**Comment by cursive-ide** [comment]
Fix released in 1.13.1-eap5 on 2023-09-25.

**Comment by cursive-ide** [comment]
Fix released in 1.13.1 on 2023-12-07.
