### ISSUE TITLE
IntelliJ IDEA 2022.1.2 REPL Pinch to zoom

### ISSUE THREAD

**Issue by hiram-madelaine** [cursive-ide/cursive#2726]
Hi ! 

I have just updated cursive to IntelliJ IDEA 2022.1.2 / 1.12.4 and I can not pinch to zoom the REPL window..
I can not use the Command + wheel mouse neither 
I am on MacOS M1

Thank you 
Best regards

**Comment by aschofie** [comment]
I am a new cursive user, but on windows the ctrl+mousewheel font size change which I have enabled in Intellij does not work in the Cursive REPL, which I do not know was ever a feature (although this issue seems to imply it), but it feels very anachronistic not being able to do so.   

IntelliJ IDEA 2022.3 (Ultimate Edition)
Build #IU-223.7571.182, built on November 29, 2022

**Comment by cursive-ide** [comment]
I'm not sure what is meant here by pinch to zoom, but I've fixed the mouse wheel zoom, and I'm hopeful that that change will also have fixed other zoom types.

**Comment by cursive-ide** [comment]
Fix released in 1.13.1-eap9 on 2023-11-27.

**Comment by hiram-madelaine** [comment]
Thank you very much for fixing this issue. It looked like nothing but for me it was very annoying !

**Comment by cursive-ide** [comment]
Fix released in 1.13.1 on 2023-12-07.
