### ISSUE TITLE
Error resolving dependencies with Leiningen 2.11

### ISSUE THREAD

**Issue by marcobiscaro2112** [cursive-ide/cursive#2879]
Steps to reproduce: 
1. Set Leiningen version to latest stable (2.11.2)
2. Import any Leiningen project (may be a freshly created with `lein new`)

<img width="421" alt="image" src="https://github.com/cursive-ide/cursive/assets/196153/52d38f8f-5049-4c8c-8d29-356e1f22ae86">

<img width="378" alt="image" src="https://github.com/cursive-ide/cursive/assets/196153/d0f12595-91aa-48a1-a8b4-306e2db02700">

**Comment by cursive-ide** [comment]
I've investigated this a bit, and it's due to the upgrade in Pomegranate (which it looks like you did!). It affects lein 2.11+. I'll have to investigate this since the Pomegranate upgrade upgraded the Maven Resolver, and some of the internal classes which Cursive uses have changed or gone. But I'll get it into the next release for sure. Unfortunately the workaround is to use 2.10 in the meantime (which means your fixes won't work, sorry).

**Comment by cursive-ide** [comment]
Fix released in 1.13.2-eap4 on 2024-02-27.

**Comment by cursive-ide** [comment]
Fix released in 1.13.2 on 2024-04-04.
