### ISSUE TITLE
Variable names are altered in the debugger

### ISSUE THREAD

**Issue by bellkev** [cursive-ide/cursive#311]
If I have a let-bound variable called, say my-shiny-var, then it appears in the debugger as my_shiny_var, and it has to be referenced this way if I want to use it while evaluating an expression.

I'm sure this, along with the fact variables like "this" and various gensyms show up in the debugger are due to how Clojure vars are represented in the underlying jvm runtime, and I imagine it may be very difficult to modify, but it would certainly make the symbolic debugging experience smoother if var names were more faithful to their Clojure names.

**Comment by cursiveclojure** [comment]
So I've spent some time looking into this, and unfortunately I don't think the debugger can be customised in this way. There is some good news though, expression evaluation is fixed in the next build and there at least variables (including closed-over variables) can be referred to by their correct source names. I'll re-open this if I ever figure out how to do this in the future.

**Comment by cursive-ide** [comment]
This is now possible in recent IntelliJ versions, and is fixed for the next build.
