### ISSUE TITLE
Add feature to run test.check defspec under caret

### ISSUE THREAD

**Issue by danielcompton** [cursive-ide/cursive#632]
"Run test under Caret in REPL" doesn't work on test.check defspecs, but running the whole ns test works fine. I'm not sure whether this is a matter of just recognising the defspec form and whitelisting it to run the test, or if there's a lot more behind it. I suspect the latter :)

**Comment by martinraison** [comment]
+1

**Comment by griff** [comment]
It would be really amazing if Cursive supported the test macros in test.chuck as described here: http://blog.colinwilliams.name/blog/2015/01/26/alternative-clojure-dot-test-integration-with-test-dot-check/
Right now the reporting is broken.

**Comment by martinraison** [comment]
Another very minor issue regarding `defspec`: I tried to use the new "Resolve as..." feature to say "Resolve defspec as def". It works, but the name of the test is marked as unused (because tests are only defined and not used anywhere).

It would be nice to be able to say "Resolve as deftest". But then if you're planning to add first-class support for `defspec` it's even better :)

**Comment by DjebbZ** [comment]
You can resolve it as `deftest`. The last option of `Resolve as` is `Specify...` and let you type the name of the var you want. Just type `deftest` and you're good to go :)

**Comment by sooheon** [comment]
+1 for first class support for defspec, you can resolve it as deftest, but you will not get the nice green checkmark for passing specs ;)
