### ISSUE TITLE
Plugin 'com.cursiveclojure.cursive' failed to initialize and will be disabled.

### ISSUE THREAD

**Issue by helloaugust** [cursive-ide/cursive#688]
I got the following error. Plz help.I use IntelliJ IDEA Community Edition 14.0.2 & cursive-14-0.1.42
![image](https://cloud.githubusercontent.com/assets/1191711/5558775/7dc74ebc-8d6e-11e4-9ade-5403e92bf454.png)

**Comment by Mar11b** [comment]
Hi @helloaugust , I'm having the same issue you had. Are you able to remember your exact solution? What is "by add the step copy files to %IDEA_HOME%\plugins"?

**Comment by cursive-ide** [comment]
@Mar11b What is the exception you're receiving at startup?

**Comment by Mar11b** [comment]
I found a way to get intelliJ Community version working. I found the version I downloaded was a little out of date so I installed a newer version and it seems to be working fine now. Thanks, Colin 👍

**Comment by Mar11b** [comment]
Hi Colin,

Thanks for responding to my distress :P

Since I posted the problem I was getting, I managed to install a more
recent version of the community version. It seems ok for now :)

Thanks again
<https://get.bitmoji.com/c/1qBzK3d>



Best regards,
Maribeth Caburian



M  +61 4 1445 2921
E   Mar11beth@gmail.com

LinkedIn Page:  au.linkedin.com/in/maribethgarces/


P Please consider the environment before printing this email notice.

**Comment by cursive-ide** [comment]
No problem, I'm glad it's working!
