### ISSUE TITLE
Must there be so many keymap conflicts?

### ISSUE THREAD

**Issue by hansgru** [cursive-ide/cursive#759]
Must there be so many keymap conflicts?

I mean, since we are talking about IntelliJ, wouldn't it be possible to have Cursive the IntelliJ way too?

E.g. "wrap with xxx" has in the Cursive keymap all combinations as conflict, but IntelliJ already has "surround with": all those actions could be mapped by that one shortcut and than a number, like it's done in Java: that would mean no conflict at all, and it's something IntellijJ users already know.

**Comment by cursiveclojure** [comment]
Well, it's very difficult. I've tried to map many of the actions to the same keys as appropriate IntelliJ actions, but many of them don't really work in the same way, and they're also used in different ways. Surround is something that I use all the time in Clojure, much more than in Java, and I wouldn't want to have to use a two-key combination for it. 

Most of the actions you can map as you like, since if you're editing Clojure the Cursive actions will take priority, and otherwise the default ones will. So the conflicts in practice are not such a problem. If you find actions that could be mapped to more IntelliJ-friendly ones I'd be interested to know about them, perhaps I could have an IntelliJ keymap.

**Comment by hansgru** [comment]
> Surround is something that I use all the time in Clojure, much more than in Java, and I wouldn't want to have to use a two-key combination for it. 

I suppose it's a matter of style. I use "surround" quite allot (together with CTRL+W) in Java and other languages. 
That's fine that you tried to optimize the combinations, but IMO the default should be as the user is already used to in IntelliJ - since it doesn't have to learn anything.

> Most of the actions you can map as you like, ...

And there's the problem :). I **don't** want to map keys, not even learn how to use them: you can't expect from the user to re-learn the IDE for each separate plug-in it will install.

IMO the above should be true not only for key combinations but for how other stuff is done in the IDE too: it should be be intuitive like the rest of the IDE. Take the REPL config as an example - the user has to read documentation in order to be able to set it up :). I never had to with IntelliJ  in the last 10 years since it was always intuitive enough.

Please don't get me wrong, I think your plug-in is fantastic and would like to buy it for me and my team ASAP, but right now even if I don't have the emacs keymap configured, it feels like it: I have to learn/read  even before being able to do trivial stuff :).

**Comment by cursiveclojure** [comment]
It's probably a combination of style and also that Cursive is quite different to many other plugins. No other plugin that I'm aware of needs anywhere near the number of keybindings that Cursive does since they don't have anything like structural editing. Trying to keep ex-IntelliJ people and ex-Emacs people (who are a significant part of Cursive's user base) happy on all platforms is impossible, so someone is going to have to configure something. I could probably create surround templates to allow you to surround a form in `()`, `{}` and `[]` but that's still not going to get you very far editing Clojure code, and most structural editing commands have no IntelliJ counterpart.

If you have specific examples of things that are unintuitive, I'd be very interested to know about them since I try to keep Cursive as consistent as possible with IntelliJ. For example, what is confusing about the REPL config? It's just a run configuration like any other, right?

Thanks for the feedback BTW, it's always useful to know what people are finding difficult when getting started.

**Comment by hansgru** [comment]
> ... since they don't have anything like structural editing. 

I understand that Clojure code needs eventually this, but why force the user to edit like that? For me it's like like I'm forced to work in a "modal way" again :).

> Trying to keep ex-IntelliJ people and ex-Emacs people (who are a significant part of Cursive's user base) happy on all platforms is impossible

I have no real statistic for you, but using IntelliJ for more than 10 years with many languages I can tell you that it's much easier to get IntelliJ users to use a new plug-in than to get a user of some other IDE/editor to use IntelliJ in first place :). Different keymaps and editing modes should keep everybody happy (e.g. IntelliJ has support for various editing modes: zen coding mode for html, but also "traditional" mode).

> what is confusing about the REPL config?

 - That I have to do something to get it work, instead of just click-ing on the REPL icon on the side.  
 - Also that I have to do this config somewhere where's not related to the REPL window - in the Run config :). 
 - Also if it wouldn't be otherwise possible (e.g. some good defaults), in order to get all this done, I have to read the documentation for it, since I can't possibly figure it out myself otherwise :).

> If you have specific examples of things that are unintuitive, I'd be very interested to know about them

I'll open a ticket for each of them for easier tracking.

**Comment by cursiveclojure** [comment]
Note that you don't have to use structural editing - there's a widget in the status bar ("Structural: On") which allows you to turn it off. You can also turn it off in the Clojure settings.

I'm actually planning to have the plugin create a default REPL run configuration for Leiningen projects, so then you'll just have to click run to start it. It's harder to create a default for non-lein projects though.

**Comment by hansgru** [comment]
> It's harder to create a default for non-lein projects though.

Users would not even expect such a thing, so it's not needed :).

**Comment by cursive-ide** [comment]
I'm going to close this issue. #1863 sets up keybindings as defaults, and tries its best to avoid conflicts with existing IntelliJ actions. It's not always possible of course, but you can unbind the Clojure actions if they conflict with an IntelliJ action you use a lot. Note that the Clojure actions will also only be triggered in Clojure contexts, when editing e.g. Java code they won't take effect, of course.
